### ISSUE TITLE
What is deref?

### ISSUE THREAD

**Issue by jtremback** [omniscientjs/omniscient#100]
I see it being called all over the site and immstruct readme but there is no documentation about it

**Comment by mikaelbr** [comment]
Hi! I added more elaboration of this on the immstruct readme now: https://github.com/omniscientjs/immstruct/blob/master/README.md

Essentially it unwraps the cursor you have and give you the value it is pointing to.

```js
var s = immstruct({ foo: 'bar' });

s.cursor('foo'); //=> cursor
s.cursor('foo').deref() //=> 'bar'
```

**Comment by jtremback** [comment]
:+1:
