### ISSUE TITLE
Any way to access this.refs?

### ISSUE THREAD

**Issue by jtremback** [omniscientjs/omniscient#101]
I need to access refs to get data out of `react-native-camera`. Have not been able to find any documentation on how to do this.

**Comment by mikaelbr** [comment]
You can still use `this` as you would with normal React (if you have to).

E.g.

```js
var MyComponent = component(function (props, statics) {
  var myRef = this.refs.someRef;
});
```

Omniscient is just a very tiny syntactic sugar on top of React for only using the "render"-function, and getting props as argument. What ever you can do with vanilla React, you can do in Omniscient as well - if you want. Omniscient has this syntax to encourage to a more functional approach in view-programming.

**Comment by jtremback** [comment]
Getting `Uncaught TypeError: Cannot read property 'refs' of undefined`, when adding that line to one of the components in the todoMVC

**Comment by mikaelbr** [comment]
Are you using fat-arrow syntax, by any chance?

**Comment by jtremback** [comment]
```js
export default component(
    'TodoHeader',
    clearAfterEdit,
    ({editState}) => {
        let refs = this.refs
        function test () {
            console.log('refs', refs)
        }

        let finish = e => {
            action.addTodo(editState.get('title'));
            editState.delete('title');
        };
        let cancel = _ => editState.delete('title');

        return header({id: 'header'},
                    h1({}, 'todos'),
                    input({
                        id: 'new-todo',
                        ref: 'editBox',
                        placeholder: 'What needs to be done?',
                        onBlur: cancel,
                        onChange: e => editState.set('title', e.currentTarget.value),
                        onKeyDown: test/*handleKeyDown(finish, cancel)*/,
                        autoFocus: true}));
    });
```

**Comment by mikaelbr** [comment]
Yeah, so this is why I don't think fat-arrow is a good idea when using `this`. You're not the first one to get bitten by this ES2015/ES6 feature: https://github.com/omniscientjs/omniscient/issues/6#issuecomment-59808514

**Comment by jtremback** [comment]
Thanks, dumb mistake on my part. However, changing to this:

```js
export default component(
    'TodoHeader',
    clearAfterEdit,
    function ({editState}) {
        let refs = this.refs
        function test () {
            console.log('editbox', refs.editBox)
        }

        let finish = e => {
            action.addTodo(editState.get('title'));
            editState.delete('title');
        };
        let cancel = _ => editState.delete('title');

        return header({id: 'header'},
                    h1({}, 'todos'),
                    input({
                        id: 'new-todo',
                        ref: 'editBox',
                        placeholder: 'What needs to be done?',
                        onBlur: cancel,
                        onChange: e => editState.set('title', e.currentTarget.value),
                        onKeyDown: test/*handleKeyDown(finish, cancel)*/,
                        autoFocus: true}));
    });
```

I am not able to get the element being referenced by editBox

**Comment by mikaelbr** [comment]
You shouldn't use refs [directly inside the render-function](https://facebook.github.io/react/docs/more-about-refs.html#cautions). I'm not a big refs guy my self, but AFAIK refs are created after the render invocation, so you are probably safer doing something like this:


```js
export default component(
    'TodoHeader',
    clearAfterEdit,
    function ({editState}) {
        // In this case we can use the fat-arrow if we want
        let test  = () => console.log('editbox', this.refs.editBox);

        let finish = e => {
            action.addTodo(editState.get('title'));
            editState.delete('title');
        };
        let cancel = _ => editState.delete('title');

        return header({id: 'header'},
                    h1({}, 'todos'),
                    input({
                        id: 'new-todo',
                        ref: 'editBox',
                        placeholder: 'What needs to be done?',
                        onBlur: cancel,
                        onChange: e => editState.set('title', e.currentTarget.value),
                        onKeyDown: test/*handleKeyDown(finish, cancel)*/,
                        autoFocus: true}));
    });
```

**Comment by jtremback** [comment]
Thanks! I'll try to do an article when I'm done to explain to others. Things seem to be working for now.

I've switched to accessing `this` inside of a mixin to avoid the React doc's ominous warning:

```js
let mixin = {
    componentDidUpdate(prevProps, prevState) {
        if (!this.props.editState.has('title') && prevProps.editState.has('title')) {
            this.refs.editBox.getDOMNode().value = '';
        }
    },

    test () {
        console.log('editbox', this.refs.editBox)
    }
};

export default component(
    'TodoHeader',
    mixin,
    function ({editState}) {
        let finish = e => {
            action.addTodo(editState.get('title'));
            editState.delete('title');
        };
        let cancel = _ => editState.delete('title');

        return header({id: 'header'},
                    h1({}, 'todos'),
                    input({
                        id: 'new-todo',
                        ref: 'editBox',
                        placeholder: 'What needs to be done?',
                        onBlur: cancel,
                        onChange: e => editState.set('title', e.currentTarget.value),
                        onKeyDown: this.test/*handleKeyDown(finish, cancel)*/,
                        autoFocus: true}));
    });

```

**Comment by jeffbski** [comment]
@jtremback FYI there are many ways to reset the value of the input, a few of them are:
 - add key={uniquevalue}, everytime uniquevalue changes, react will consider this to be a new input so it will have the default value
 - control the value directly value={this.state.val}, but you need to change this.state.val on every onChange too
 - if you have a form surrounding your input, you can use the form to reset the inputs to the original value, usually I do this in form onSubmit, React.findDOMNode(formComponent).reset()

Of these choices, I like the using the key the best currently.

**Comment by jtremback** [comment]
Interesting about the key. That code was just to debug, I'm actually working with a react native camera element. Does the trick with the key work on all react elements?

**Comment by jeffbski** [comment]
Well I don't know about its use for debugging, but key is desired in the case when there is a group of child elements (you will see the warning in console if you don't provide it) so that react can efficiently determine which elements changed. So when displaying an array or sequence I try to provide the key usually using an id. I just wondered what would happen if I used key for an input and it worked how I expected.
