### ISSUE TITLE
Calling a function in the render function 

### ISSUE THREAD

**Issue by jannavarro** [omniscientjs/omniscient#103]
So I have the omniscient component below. problem is the displayMessageIfError function does not appear to get written to the DOM. I also tried variations such as { displayMessageIfError} or {displayMessageIfError()} or {this.displayMessageIfError()}

    component(function () {
        function displayMessageIfError(){
        return <div><p>Bad login information</p></div>;
     }

    return (
    <div>
        <form onSubmit={this.handleSubmit}>
          //some rendering here
          {displayMessageIfError}
        </form>
      </div>
    }

**Comment by Dashed** [comment]
Code seems invalid.

This is my interpretation and should work:

```js
component(function () {
    function displayMessageIfError(){
        return <div><p>Bad login information</p></div>;
    }

    return (
        <div>
        <form onSubmit={this.handleSubmit}>
            //some rendering here
            {displayMessageIfError()}
        </form>
        </div>
    );
});
```

**Comment by jannavarro** [comment]
@Dashed you are correct. That did work. I thought I did try that, probably I may have some typographical errors earlier. Thanks!
