### ISSUE TITLE
Omniscient Next: Thoughts on next iteration

### ISSUE THREAD

**Issue by mikaelbr** [omniscientjs/omniscient#104]
An issue for thoughts on next version of Omniscient.

1. Rewrite shouldComponentUpdate (#76) to make use of `.equals` on cursors to allow for new patterns such as creating wrapping objects (functional lenses? observables? channels?) which implements a equals method. This would break the current API, but the API surface would be much smaller. No need for `isCursor`, `isCursorEquals`, etc. It would also be much less code implementation.
2. Create new repo: `omniscient-tools`/`omniscient-hoc`, where higher order components and/or other tools can reside. A set of tools to ease development / be more opinionated. Tools can be such as higher order components for attaching immstruct references to components, partial props on components, etc.
3. Check out #89 and think if we need to have a goto-solution for best way for "talking back to parents".
4. Deprecate statics? With the `.equals` implementation from (1), there would be no need for statics. We could just have a wrapper object implementing a `.equals` method that always return `false`.

cc @torgeir @Dashed

**Comment by torgeir** [comment]
Yeah, I'm also curious on investigating @Gozala's approach from #89 some more, for those that want to do away with cursors.

**Comment by Dashed** [comment]
> higher order components for attaching immstruct references to components

I think this is important. This implementation may not be obvious to some, but if one scopes their app state through cursors, then the re-render steps should also be scoped to the Components that depend on those cursors whenever they're updated.

Here's an API sketch:

```js
// alternative to top-down rendering e.g. structure.on('swap', () => React.render(...));

const watchCursors = function(props, manual) {
    
    // get reference cursors
    const { listCursor, otherCursor } = props;

    // add validation step to re-render whenever listCursor emits a value update event
    manual(function(update) {

        // update when list has changed in size
        let prevSize = listCursor.deref().size || 0;

        listCursor.observe(function() {
            const nextSize = listCursor.deref().size || 0;

            if(nextSize !== prevSize) {
                update();
            }
        });

    });

    // return array of ref cursors to observe and re-render wrapped Component
    // whenever an event has been emitted.
    //return [otherCursor];

    // if only returning one ref cursor, may return that cursor directly.
    // sugar to [otherCursor]
    return otherCursor;
}

// assign new props to be merged with either:
// - nextProps (through componentWillReceiveProps, when parent component re-renders)
// - this.props (through internal ref cursor listener when any ref cursor emits an event)
//
// This function is useful for 'resolving' cursors into actual prop values passed to
// Component whenever it re-renders. Instead of relying on potentially stale cursors, you
// provide new prop values using ref cursors through the higher-order component.
// Working with prop values is simpler to work with from the Component's perspective.
// For this model to work, one shouldn't be deref()ing in render()
const assignNewProps = function({listCursor, otherCursor}) {
    
    return {
        list: listCursor.cursor().deref(),
        otherVal: otherCursor.cursor().deref()
    }
}

const WrappedComponent = hoc(Component, watchCursors, assignNewProps);
```

**Comment by Dashed** [comment]
I'm totally against (1). This is pretty much like `Immutable.is(foo, bar)` which is way more expensive than simply `foo === bar`; we might as well not bother with immutable structures in the first place.

I understand the rationale to support for this case:
```js
Immutable.List.of(1, 2) == Immutable.List.of(1, 2) // => false
Immutable.List.of(1, 2).equals(Immutable.List.of(1, 2)) // => true
```

But practically, `shouldComponentUpdate` is on the hot path. And even the immutable library doesn't use `is(...)` internally: https://github.com/facebook/immutable-js/blob/e5085a579d873b419ca03d1112e1e5c30170ba01/src/Map.js#L766

----

One can make `Immutable.List.of(1, 2) == Immutable.List.of(1, 2)` be a rare occurrence if they stick to using the same root between re-renders, and have `.update()` to actually use inputs (e.g. `update((x) => x.op())`) instead of completely replacing existing immutable structures entirely new ones.

**Comment by mikaelbr** [comment]
I mis-remembered, but I thought we concluded that the real life implications were marginally, as the `hashCode` was generated and it used to check instead. But after some checks it really is a huge difference (http://jsperf.com/immutable-equals). Way too bad, because the code simplifications and potential powerful patterns is very appealing to me.

For reference, here's some of the fairly straight forward checks I did: http://jsperf.com/immutable-equals

**Comment by Dashed** [comment]
@mikaelbr Is immstruct part of this envisioned next iteration?

**Comment by mikaelbr** [comment]
I think Immstruct has it's own thing. We see a lot of people using Immstruct but not Omniscient (for instance, you) and What I'd call the next iteration for Omniscient is more about taking the lessons learned from the API and usage with Omniscient 3.0.0, and see how we can improve it.

So, API-wise, there are few "major" points I'd like to revise/check if we can do it better:
1. Statics. What should we do with them? I feel the `statics` property is a too loose/brittle API.
2. Talking back to parents. This might not be a exclusively API-thing, but a combination of clear API and a "recommended way" of doing things.
3. Fewer method overrides. While powerful, I think the `.equals` way was simpler and more elegant.

The last thing I want to improve on is a more opinionated toolset for Omniscient + Immstruct. This to make it easier to get started and for "every day" development. One of Omniscient/Immstructs strength (IMO) is flexibility and versatility. But this can also be a pain point for new adopters. So we need examples, helper components and good documentation to make this better.

Only thing I've noted that needs to be checked for Immstruct is the key path alteration on references. That it might send the wrong keyPath on observers. Also some improvements on the docs. Is there anything else you can think of that it lacks for version 2, @Dashed ?


What I envision is the following: Omniscient 4, Immstruct 2 and Omniscient HoC. Omniscient 4 is really just a simplified API (less method overrides?). Immstruct 2 with the increased power with references, and Omniscient HoC that binds these two more tightly together. 

Now when we see that `.equals` won't work too good, it might seem as the Omniscient API won't break as I first thought, so it might be that we get a minor release instead (which can be good).

**Comment by Dashed** [comment]
> Only thing I've noted that needs to be checked for Immstruct is the key path alteration on references.

`newValue` and `oldValue` should also be w.r.t to ref cursor's keypath.

>  Is there anything else you can think of that it lacks for version 2, @Dashed ?

I think the overhauled event propagation would be fine for v2; probably just needs more polishing. At the moment, I don't really see anything new that would fit into a v2 release.

I'd like to suggested considering a custom cursor implementation (merge structure/cursor/ref cursors as  one extendible type). But this may be more suitable for v3 (and beyond). 

-----

Regarding `statics`, why not alias them as `contexts`? 
https://www.tildedave.com/2014/11/15/introduction-to-contexts-in-react-js.html

They're not officially documented on React's docs. But omniscient internals may use it [contexts], and disguise it as `statics`.

**Comment by Dashed** [comment]
> Talking back to parents. This might not be a exclusively API-thing, but a combination of clear API and a "recommended way" of doing things.

These are the patterns I have so far come across:

I think one way of doing this is flux (top-down rendering):

0. subscribe cursor (data dependencies) to re-render a component (usually root component)
1. call flux store
2. store modify/transform on a cursor

Using Omniscient HoC or something similar, you can shrink your top-down rendering apth to instead refresh some descendent component. This is done by explicitly declaring some cursors as a dependency of a component. 

-----

Another way is create and treating immstruct Structures as flux stores, and localizing it:

```js
const WrappedComponent = React.createClass({
    getInitialState() {

        const local = immstruct({
            current: null
        })

        return {
            local: local,
            current: local.reference('current')
        };
    },

    render() {
        const {items} = this.props;
        items = items.map(Item => <Item current={this.state.current}>);

        return (
            <List>
                {items}
            </List>
        );
    }
});
```

Reference pattern: https://facebook.github.io/react/tips/communicate-between-components.html

Above is sugar to:

1. manually creating callbacks that modify some centralized state
2. bind callbacks to parent component (usually to call `this.setState` or something)
3. passing callbacks as props

Pros for this pattern is that It is easy to avoid re-rendering the parent (and thus the children) whenever you modify local state; and as well as being able to re-render relevant subset of children components.

**Comment by gilbox** [comment]
Some thoughts:

1. Next react is supposed to support plain functions as components. Maybe this will effect omniscient architecture decisions?
2. I'm now designating `statics` with an es7 decorator, so all statics are just regular props and there is no `statics` prop necessary. See [here](https://github.com/gilbox/elegant-react#usage) and [here](https://github.com/gilbox/elegant-react/blob/master/src/create-elegant-decorator.js#L10)
3. I'm now using a [higher-order component](https://github.com/gilbox/elegant-react/blob/master/src/create-elegant-decorator.js#L30) instead of mixins to handle `shouldComponentUpdate`, and statics delegates. It's actually simplified the logic quite a bit. Not sure yet I there are any negative implications.

**Comment by mikaelbr** [comment]
Good thoughts!

1. Yeah, that was the plan all along. Excited about this one! I'm leaving for a longer vecation, so won't be able to rewrite it right away, but I'm looking forward to do it!
2. Thats a good idea. Would make for a more explicit API. But I'm not the [biggest fan of python style decorators](http://mikaelb.net/2015/04/03/breaking-existing-behaviour-to-avoid-function/), and as for now you don't have to transpile Omniscient. Kind of the central focus is functions. Not saying it will not use es6 for ever, and omniscient next might even use it, but I still think functions will do as we just use function expressions as components.
3. Thats pretty much just an abstraction of using mixins or object methods, and I dont think it has much implications for the end user. the end user could still use HoCs to override SCU though! One potential negative implication is that you would have double all components, and causing more object clean up for the GC.

**Comment by Dashed** [comment]
> One potential negative implication is that you would have double all components, and causing more object clean up for the GC.

This is a consequence for the push towards the HoC mandate that the react team is encouraging. This isn't a big deal if a HoC can be constructed using a plain function/plain object.

**Comment by mikaelbr** [comment]
Thats a good point. You wont have to create several components.

**Comment by gilbox** [comment]
Thanks for the link to your wonderful article mikaelbr, I agree that the complexity of the addition of `class` is unfortunate, and I kind of wish it didn't exist either. So admittedly, using *class*es I'm going with the flow here since that's the direction React seems to be going. 

>  I dont think it has much implications for the end user. the end user could still use HoCs to override SCU 

Very true. However, I like that it feels more straight-forward to me. I can define SCU exactly where I'm used to doing it, in the component itself, knowing that the optimization provided by the decorator is applied regardless of what I do in my own SCU.

**Comment by mikaelbr** [comment]
I took a small break in my vacations to test out an ignorable-decorator. Seems to me to work as expected.

```js
var React = require('react');
var component = require('./');
var shouldUpdate = require('./shouldupdate');

module.exports = function (fields, Component) {
  fields = arrify(fields);
  var isJSX = !Component.jsx;

  var IgnoredComponent = component('IgnoredFields' + Component.displayName, {
    shouldComponentUpdate: shouldUpdate.withDefaults({
      isStatics: function (item, key) {
        return fields.indexOf(key) !== -1;
      }
    })
  }, function (props) {
    if (isJSX) {
      return React.createElement(Component, props);
    }
    return Component(props);
  });

  return isJSX ? IgnoredComponent.jsx : IgnoredComponent;
};

function arrify (prop) {
  if (Array.isArray(prop)) return prop;
  return [prop];
}
```

Something like this, if not this, will probably be the next `statics` I think. A much cleaner and more explicit API.

---

> Thanks for the link to your wonderful article mikaelbr, I agree that the complexity of the addition of class is unfortunate, and I kind of wish it didn't exist either. So admittedly, using classes I'm going with the flow here since that's the direction React seems to be going.

I don't necessarily apply to the thought that you have to use React with "classes". And https://github.com/facebook/react/pull/3995 kind of help me sustain that conviction.

---
> > I dont think it has much implications for the end user. the end user could still use HoCs to override SCU

> Very true. However, I like that it feels more straight-forward to me. I can define SCU exactly where I'm used to doing it, in the component itself, knowing that the optimization provided by the decorator is applied regardless of what I do in my own SCU.

I mean, you can, with the current implementation as well, easily use HoCs (or [`ad-hocs` as I jokingly tried to coin them](https://twitter.com/mikaelbrevik/status/613294026838704128)) to override `shouldComponentUpdate` as well:

```js

var MyComp = component(/* */);

var MySpecializedComp = component({
  shouldComponentUpdate: function () { /* */ }
}, function (props) {
  return MyComp(props);
});
```

And I've always thought of this as the "best practise approach". Creating a more specialized *derived* component, from a maybe more general one, **iif** there is a need for a more general one. Omniscient using mixins internally for setting SCU thought matter for the end user of Omniscient Components. Makes sense?

**Comment by gilbox** [comment]
@mikaelbr I agree with everything you said, however my point about `shouldComponentUpdate` and HoC's still stand:

> the optimization provided by the decorator is applied **regardless of what I do in my own SCU**

in contrast, you override SCU in the example above. I just think that the compositional approach with SCU is superior to overriding it (although this conviction could easily change at any time).

**Comment by mikaelbr** [comment]
I don't quite follow. So in the HoC example from above, the inner SCU will still work, if it is more restrictive than the one in an outer layer. Say if the top one always returns true, it will be a "shallow" component, as it will always just use the one from the decorated component.

**Comment by gilbox** [comment]
Yep, that's it. I'm just saying I find it's usually more useful to augment omniscient's SCU, not override it. But if I want to override it, I just don't use the decorator and define my own instead.

**Comment by mikaelbr** [comment]
This issue is superseded by #116
