### ISSUE TITLE
Omniscient does not load with React Native

### ISSUE THREAD

**Issue by samvit** [omniscientjs/omniscient#106]
Steps to reproduce the problem:

```
react-native init hello
cd hello
```

The app now opens and loads properly

```
npm install --save omniscientjs/omniscient#react-native
```

App does not load anymore

**Comment by samvit** [comment]
Non-issue now: react-native migration to babel fixes this

**Comment by mikaelbr** [comment]
Thanks for the follow-up. DIdn't get a chance to look at this. Do you know what caused it?
