### ISSUE TITLE
example page not working

### ISSUE THREAD

**Issue by jpatel3** [omniscientjs/omniscient#107]
http://omniscientjs.github.io/examples

Its listed as demo link for Basic Tutorial: Creating List with Live Filtering JSX Edition. It's not working.

**Comment by mikaelbr** [comment]
Hi! Is this in the wiki or on [the page](http://omniscientjs.github.io/tutorials/02-editing-basic-tutorial-creating-list-with-live-filtering-jsx-edition/)? All documentation is moved to the homepage, and is only on the wiki for historic reference. Tried to illustrate this on the top of the articles in the wiki, but it can probably be more explicit.

**Comment by jpatel3** [comment]
It was on this page in the last paragraph - https://github.com/omniscientjs/omniscient/wiki/Basic-Tutorial:-Creating-List-with-Live-Filtering---JSX-Edition

I am able to access it now from the link you posted.

**Comment by mikaelbr** [comment]
I updated the wiki-article to show that it is deprecated. Thanks for reminding me!
