### ISSUE TITLE
Omniscient tutorial, unable to load data lazily

### ISSUE THREAD

**Issue by ByScripts** [omniscientjs/omniscient#110]
Hi there,

I followed the [Tutorial](http://omniscientjs.github.io/tutorials/01-editing-basic-tutorial-creating-list-with-live-filtering/) and it works fine.

But now I'm trying to load data lazily.

So here is my structure:

    var structure = immstruct({
        search: '',
        libs: []
    });

And for testing, here is how I load data lazily (I shortened the list):

```
setTimeout(function(){
    structure.cursor('libs').update(function(){
        return [
            {title: 'Backbone.js', url: 'http://documentcloud.github.io/backbone/'},
            {title: 'AngularJS', url: 'https://angularjs.org/'}
        ];
    })
}, 2000);
```

But it doesn't work.

Inside the `Matches` component, if I log `cursor.get('libs')` I get:

- At loading time: an IndexedCursor
- After 2 seconds, when data is loaded lazily: A simple JS array

Is that a bug ? Or am I doing something badly ?

What is the "good way" to load the data lazily ?

Thank you.

**Comment by torgeir** [comment]
Hi!

Its because an Immutable js cursor's `update` callback is expected to return an Immutable js datastructure. Wrap your array of libs in `Immutable.fromJS([..])` and [you should be good to go](http://goo.gl/LrZqJm)

Hope that helps!

**Comment by ByScripts** [comment]
Ok I see, thank you.

Where does Immutable come from in this case ?

I can add Immutable to my package.json, then do a `var Immutable = require('immutable')` but is it the right thing to do since immutable is already a dependecy of Omniscient ?

**Comment by torgeir** [comment]
Its required implicitely for convenience in the playground, so you'll need a dependency and an import, yes

**Comment by mikaelbr** [comment]
> I can add Immutable to my package.json, then do a var Immutable = require('immutable') but is it the right thing to do since immutable is already a dependecy of Omniscient ?

NPM handles that for you. If your package is dependent on Immutable.js and Immstruct needs Immutable.js and they match each others version range (immstruct has a "loose" version range so it matches many versions), the same Immutable.js is used.

**Comment by ByScripts** [comment]
Works fine, thank you.
