### ISSUE TITLE
How to use childContextTypes

### ISSUE THREAD

**Issue by jannavarro** [omniscientjs/omniscient#111]
So in React there are contextTypes defined this way:

    React.createClass({
    
    childContextTypes: {
         name: React.PropTypes.string.isRequired
    },

    getChildContext: function() {
         return { name: "SomeName" };
    },
    //....

How can these be done via omniscient? Somethign like this does not work:

    component(function(){
    
    childContextTypes: {
         name: React.PropTypes.string.isRequired
    },

    getChildContext: function() {
         return { name: "SomeName" };
    },

**Comment by Dashed** [comment]
Through mixins.

**Comment by mikaelbr** [comment]
If you want, you can create Omniscient components almost the same as any other React component, by passing in what methods you want. So in your example it would be:

```js
component({
  childContextTypes: {
    name: React.PropTypes.string.isRequired
  },
  getChildContext: function() {
    return { name: "SomeName" };
  }
}, function () {
  // Render function
});
```
