### ISSUE TITLE
Docs: unused mixin in readme example

### ISSUE THREAD

**Issue by BrainCrumbz** [omniscientjs/omniscient#113]
Hello there.
Not sure if we missed something, still new to Omniscient, but it looks like a code example in readme.md defines a mixin that then is never actually used.

In section [Talking back from child to parent](https://github.com/omniscientjs/omniscient#talking-back-from-child-to-parent) `mixins` variable is defined but not passed to any further component. 

Is that intended? Regards

**Comment by mikaelbr** [comment]
Hi! You are totally right. It should be included. I've updated the readme now. Thanks for letting me know! :cake:

**Comment by BrainCrumbz** [comment]
yumm, cake-driven contributions!
