### ISSUE TITLE
Inline Editable Tree example, inputs losing focus onChange

### ISSUE THREAD

**Issue by spencerliechty** [omniscientjs/omniscient#115]
https://gist.github.com/spencerliechty/9cde417ed43f751a3757

Hey there,

I'm working through some examples using omniscient-starter-pack as a base. I'm currently working to add inline edits to a basic tree structure. 

I deviated from the example (http://omniscientjs.github.io/playground/01-inline-edit/) by moving component state to an immutable. In the example, the 'editing' state is part of the component and I'm trying to avoid keeping ANY state in components if possible.

My issue is: when a user changes the value in the input element, (it appears as if) the element is mounted and the input element loses focus. 

So:
1) Is a re-mount expected when the immutable state is updated?
2) Is it even possible to implement this without keeping the component stateful to the extent that it is internally aware when/if it is in 'editing' state?
3) Could this have something to do with omniscient's shouldComponentUpdate()?

Thanks!

**Comment by torgeir** [comment]
>  Is a re-mount expected when the immutable state is updated?

I like your thinking :)

> Is it even possible to implement this without keeping the component stateful to the extent that it is internally aware when/if it is in 'editing' state?

Yes, indeed!

The remount is triggered because your keys change as part of changing the text for each node.  React uses this id to keep the state of each component (internally) in sync with your actual html. Try changing your example to use keys not dependent on the text of each node, but rather e.g. its place in the list.

**Comment by torgeir** [comment]
Here's an [example using list indices](http://goo.gl/6cLk8Z). If the data of each node has some other unique id you might as well use that.

**Comment by spencerliechty** [comment]
:+1: :+1: :+1: ty @torgeir, I assumed it was my code breaking it, thanks for showing me where!

**Comment by torgeir** [comment]
Np, glad to help!

Relevant reading https://facebook.github.io/react/docs/reconciliation.html
