### ISSUE TITLE
Is it right that there's no local state?

### ISSUE THREAD

**Issue by polkovnikov-ph** [omniscientjs/omniscient#120]
Following [this lines](https://github.com/omniscientjs/omniscient#updating-output) I find it quite unpleasant to create all the local state (i.e. active menu items) on top-level. This makes the changes in the code non-local: I have to modify a component and the application root too.

I could imagine a way to recursively ask children to put their local parts of the state into the global state. That could be a method that is getting called some time prior to the `render` call. Though I guess you have seen this problem too, and there is an obvious way to tackle this problem I don't see.

Is there a way to fix ad-hoc initial state creation?

**Comment by mikaelbr** [comment]
You can use local state if that makes sense. Omniscient doesn't enforce any regulation on `setState`, but encourages to think about what is local and what is global. If the data is view specific and it doesn't make sense for the application state to store it, use local view state. If you want it "predictable" (by taking input), pass the state as input. Hope this helps clear things up.

**Comment by polkovnikov-ph** [comment]
@mikaelbr Yes, I've tried to add it via the mixin, but thought that this thing is alien for `omniscient` (it's mentioned that the library is for the _stateless_ components in the first lines on the front pahe). What do you mean by state being "predictable"?

**Comment by mikaelbr** [comment]
> Yes, I've tried to add it via the mixin, but thought that this thing is alien for omniscient (it's mentioned that the library is for the stateless components in the first lines on the front pahe).

Yeah, Omniscient encourages use of stateless components where ever it makes sense, but in the cases where you need state (there are some cases where that is required), you are free to use so, by attaching functions to the component. :smile: 

> What do you mean by state being "predictable"?

"Predictable" as in referentially transparent / pure. Given the same input, it should produce the same output. By having view state, you can sometimes run the same code twice, and the second time have a different output than the first time.

**Comment by polkovnikov-ph** [comment]
Will `omniscient/shouldupdate` realize that the component should be rerendered if I call `this.setState`?

**Comment by mikaelbr** [comment]
Yes. The provided `shouldComponentUpdate` [takes state into account](https://github.com/omniscientjs/omniscient/blob/master/shouldupdate.js#L81-L84) :+1: .

**Comment by polkovnikov-ph** [comment]
Sorry, I forgot that I could just take a look in the source. There is `_isEqualState`.

**Comment by polkovnikov-ph** [comment]
Well, I was a bit slower :)

Thank you.
