### ISSUE TITLE
Update in componentWillMount

### ISSUE THREAD

**Issue by polkovnikov-ph** [omniscientjs/omniscient#131]
If the update on the cursor passed via props is triggered in `componentWillMount`, there is no modifications visible in `render`. React documentation states that changes in `state` should be visible in a `render` call afterwards, but doesn't state what should happen if `props` got changed. Is it a correct behaviour? If not, what's an idiomatic way of initializing a global state with the same lifetime as given component?

**Comment by mikaelbr** [comment]
Changes inside `componentDidMount` through e.g. immstruct should simply cause a new render loop to occur, thus cause the component to have access the props. You couldn't have access to it in the same, immediate, render loop, as the values are immutable and in that case you would have a reference to the old data. One way to circumvent this is to use immstruct references, but that feels nasty, and I'd rather just allow for another render loop iteration.
