### ISSUE TITLE
Change API for overriding internal checks

### ISSUE THREAD

**Issue by mikaelbr** [omniscientjs/omniscient#36]
Implement something like `withSettings`.

It would still be, for 95% of the cases:

```js
var component = require('omniscient');
```

But if you want to override any methods, instead of:

```js
var component = require('omniscient');
component.isEqual = function () { ... }
```

you do:

```js
var component = require('omniscient').withSettings({
   isEqual: function () { ... }
});
```

Much cleaner API, in my mind. Also less error prone.

First add deprecation notice on existing API, but remove existing API at next major release (`v3.0.0`).

I think the global override should be more of a user choice/implementation, and it's just to brittle. Would't want Omniscient to rely on a major magic state that you have defined in one of your modules. That's essentially a huge side-effect.

A better solution, by my opinion, would be to make a defaults module your own:

```js
// defaultOmniscient.js
module.exports = require('omniscient').withSettings({
  // my defaults
});

// some module:
var component = require('./defaultOmniscient');
// ...
```

I think this is a much more robust and "reason-able" approach.

**Comment by Dashed** [comment]
Sweet.

I still want to be able to override deepEqual though. This may require `isEqualState` to be an inline function.

**Comment by Dashed** [comment]
Nevermind, forgot about https://github.com/omniscientjs/omniscient/issues/34

**Comment by mikaelbr** [comment]
Yrah, thats a seperate issue :) Fixing it in the morning. But with this patch, I think the usage of overriding defaults makes much more sense and is alot more predictable and robust.
