### ISSUE TITLE
Test example

### ISSUE THREAD

**Issue by pasviegas** [omniscientjs/omniscient#38]
Would be nice to have an example on how to properly test a component. 
At least I couldnt find one in the other example repos :)

Thanks

**Comment by Dashed** [comment]
You can test them in pretty much in the similar manner as shown here: http://facebook.github.io/jest/docs/tutorial-react.html#content

**Comment by torgeir** [comment]
Alternatively it is possible to test components against jsdom like in the tests for omniscient itself, though it's setup is kind of hairy to work around quirks of reactjs when using jsdom https://github.com/omniscientjs/omniscient/blob/master/tests/integration-test.js

**Comment by mikaelbr** [comment]
Closing this as examples are provided. Please let me know if further examples and info is required!
