### ISSUE TITLE
omniscient should unbox cursors before calling render if that's only thing that was passed.

### ISSUE THREAD

**Issue by Gozala** [omniscientjs/omniscient#43]
I find it confusing that if I do `App(cursor)` my App component needs to grab `props.cursor` instead of just receiving a cursor, while if I do `App({ x: xCursor, y: yCursor })` I can just get cursors as `x` & `y`. I think it would be a lot better if omniscient would unbox cursor if that's what was passed to a component.

**Comment by mikaelbr** [comment]
Hi! Yeah, that's a pretty good idea - and something we actually had before Omniscient v2. But we saw that it could cause confusion and the inconsistent usage was a bit surprising. "Behave in this way, expect when X, and except when Y, etc" might be a bad pattern to follow IMO and we should try to do the path of least surprises and consequent behaviour.

What I see many do (with ES2015 lisp style [destructuring](http://git.mikaelb.net/presentations/bartjs/destructuring/#/4/4)) is something like:

```js
var Comp = component(function ({ cursor }) {
  // cursor will point to this.props.cursor
});

// or with more cursors:
var Comp2 = component(function ({ x, y }) {
  // use cursor x and y
});
```

This way you can still have `statics` (passed values not causing a update):

```js
var Comp = component(function ({ cursor }, statics) {
  // use cursor and access statics
});

// or with destructuring:
var Comp2 = component(function ({ x, y }, { myStaticValue }) {
  // access all the values
});
```

Unfortunately, this will require a ES2015 transpiler - which isn't ideal, but I think it's the best we can do.

**Comment by Gozala** [comment]
> Hi! Yeah, that's a pretty good idea - and something we actually had before Omniscient v2. But we saw that it could cause confusion and the inconsistent usage was a bit surprising. "Behave in this way, expect when X, and except when Y, etc" might be a bad pattern to follow IMO and we should try to do the path of least surprises and consequent behaviour.

"least surprises and consequent behaviour" is exactly what I would like to do as well. To me passing `x` and getting `{cursor: x}` is very surprising, while passing `{x, y}` I do get `{x, y}` (where `x` and `y` are cursors. Does that make sense ?

**Comment by Gozala** [comment]
> This way you can still have statics (passed values not causing a update):
```js
var Comp = component(function ({ cursor }, statics) {
  // use cursor and access statics
});
// or with destructuring:
var Comp2 = component(function ({ x, y }, { myStaticValue }) {
  // access all the values
});
```

I am not clear on how sure why what I suggest affects that, could you please elaborate.


P.S.: I submitted # #44 just to illustrate how I imagined this, had to make it more clear

**Comment by mikaelbr** [comment]
Ah, I didn't think of it as passing in `Comp(cursor)`, in that case it is actually "more correct" to give cursor as the first argument. So using the component without JSX, you could possibly expect to get just a cursor.

Any thoughts on this, @torgeir ? I think I'll do some implementation and feel it out, and possibly rather revert it if @torgeir has some good arguments against.

About the statics thing: I interpreted this:
> while if I do App({ x: xCursor, y: yCursor }) I can just get cursors as x & y

As you would get something like:
```js
var Comp = component(function (x, y) {
  // use cursor and access statics
});
```

But that would possibly get a bit weird with statics.

**Comment by Gozala** [comment]
> About the statics thing: I interpreted this:
> 
>     while if I do App({ x: xCursor, y: yCursor }) I can just get cursors as x & y
> 
> As you would get something like:
> 
> var Comp = component(function (x, y) {
>   // use cursor and access statics
> });
> 
> But that would possibly get a bit weird with statics.

Oh yeah that's not what I was suggesting in case of `Comp({x: xCursor, y: yCursor})` I think in that case it should be like:

```js
var Comp = component(function ({x, y}) {
   // use cursor and access statics
});
```

**Comment by Gozala** [comment]
To put it differently I am suggesting to update behavior only for a case where only thing you pass in is cursor. I believe that's also what my change does in a pull. If that works I'll update test to match that new behavior.

**Comment by mikaelbr** [comment]
Yeah, I get that :smile: . I'm just initially a bit skeptical to `isJustCursor@omniscient` - and especially exposing it on props. But going through it myself, I don't know if it's a better way of doing it, to not have the change work on JSX examples.

One way to do it is to move the `createClass` part inside creat, but I don't think that's a better solution, as it would create different class types.

I think maybe your solution is the best one, but `isJustCursor@omniscient` should really be removed from the props object :+1: . Go ahead and update tests and add specific tests in your PR and we'll take it from there.

**Comment by Gozala** [comment]
> Yeah, I get that  . I'm just initially a bit skeptical to isJustCursor@omniscient - and especially exposing it on props. But going through it myself, I don't know if it's a better way of doing it, to not have the change work on JSX examples.

I think another solution would be to always box passed props not just in case of `isCursor(props)` as it is now, that way `isJustCursor` won't be necessary and `render` will always unbox.

> I think maybe your solution is the best one, but isJustCursor@omniscient should really be removed from the props object :+1: . Go ahead and update tests and add specific tests in your PR and we'll take it from there.

I'm not sure I follow what you are suggesting, do you mean `delete this.props[isJustCursor]` in render ?

**Comment by mikaelbr** [comment]
> I'm not sure I follow what you are suggesting, do you mean delete this.props[isJustCursor] in render ?
Pass on a props with isJustCursor filtered out.

**Comment by Gozala** [comment]
If it was up to me I would personally do something along this lines:

```js
var baseRender = function() {
      if (debug) debug.call(this, 'render');
      return this. omniscientRender(props.input, this.props.statics);
}

function component (displayName, mixins, render) {
  var options = createDefaultArguments(displayName, mixins, render);
  var methodStatics = pickStaticMixins(options.mixins);

  var componentObject = {
    displayName: options.displayName,
    mixins: options.mixins,
    render: 
    omniscientRender: render
    
  };

....

 var create = function (key, input) {
    var children = toArray(arguments).filter(React.isValidElement);

    if (typeof key === 'object') {
      input = key;
      key   = void 0;
    }

   var props = {input: input};
   
    if (key) {
      props.key = key;
    }

    if (!!children.length) {
      props.children = children;
    }

    return React.createElement(Component, props);
  };
```

**Comment by Gozala** [comment]
Ok I was not able to figure out what did you meant by:

> Pass on a props with isJustCursor filtered out.

There for I went ahead with slightly different route that would not use `isJustCursor` at all, instead now it uses `props[component.cursor]` as a field where cursor is stored in cases where it's only thing passed to component. Presence of `this.props[component.cursor]` is also used as a signal to render method that only thing passed was a cursor, in which case it get's unboxed before it's passed to user defined `render`.

This way only thing that has changed for `omniscient` perspective is that `this.props.cursor` got renamed to `this.props[component.cursor]`. Please not that `component.cursor` is set to `"{{private:cursor@omniscient}}"` and the ugliness is intentional to avoid unboxing in case user did `Component({cursor: foo})`.

I hope all this makes sense.

P.S.: All tests pass now too.

**Comment by Dashed** [comment]
So I took a look at the PR. I can't be too vocal on my opinions, because I don't actually use omniscient for component creation (I just wrap the awesome `shouldComponentUpdate`); and I only primarily use JSX.

---

The `{{private:cursor@omniscient}}` cursor key to box/unbox is so hacky. Ideally, ES6 Symbols should be used instead. 

I like the idea though, and it was once a minor pet peeve on my early usage of omniscient.

I'm wondering if this is something that should go to userland. For example, if we can have some way to execute user-defined functions at these locaitons:

- https://github.com/Gozala/omniscient/blob/a0dc6b5a37d7f7ee6a8bb55a26dc4380b726d27e/component.js#L36

- https://github.com/Gozala/omniscient/blob/a0dc6b5a37d7f7ee6a8bb55a26dc4380b726d27e/component.js#L80

You can do features like unboxing/boxing externally.

**Comment by Gozala** [comment]
> The {{private:cursor@omniscient}} cursor key to box/unbox is so hacky. Ideally, ES6 Symbols should be used instead. 

I agree, but I'm afraid neither browser nor react is ready for ES6 Symbols, so this was kind of ad hock symbols if you like.

**Comment by Gozala** [comment]
> I'm wondering if this is something that should go to userland. For example, if we can have some way to execute user-defined functions at these locaitons:

>    https://github.com/Gozala/omniscient/blob/a0dc6b5a37d7f7ee6a8bb55a26dc4380b726d27e/component.js#L36

 >   https://github.com/Gozala/omniscient/blob/a0dc6b5a37d7f7ee6a8bb55a26dc4380b726d27e/component.js#L80

> You can do features like unboxing/boxing externally.

I don not think this belongs in the user land, since it's just strange to have an api that sometimes passes argument as is and other times it passes as `{cursor: argument}`. If this feels too magical or wrong other alternative could be to disallow passing a cursor all together so that users will be forced to doc `App({cursor: cursor})` instead at least that way API is will be consistent in a sense that what you pass to component that's what you get in a function.

**Comment by Gozala** [comment]
I personally would prefer to have boxing / unboxing built in though, since otherwise I'd just implement my own `component` function since mixins and other stuff that component does in not something I'm interested in (specially since react is moving off mixins).

**Comment by torgeir** [comment]
Yes, I'm all for this except the obscure variable name! Simplifies working without jsx like the initially intended syntax and offers less surprise.

**Comment by mikaelbr** [comment]
Rebased in fd5fa10c0dc38ed3ebe2516c5e23552ba337e278. I also think this should be default behaviour. Symbols could probably be used some time in the future, but until then I think it's better to have an explained variable name with the convention of "private properties" (underscore prefix).

Thanks for the discussion, feedback and contribution!
