### ISSUE TITLE
Expose isCursor on ComponentCreator

### ISSUE THREAD

**Issue by phated** [omniscientjs/omniscient#51]
During the refactoring, it seems like `isCursor` was removed from the exported object.  Since it is able to override `isCursor` in the new implementation, I think it would be a good idea to attach it to the ComponentCreator.

I am working on a library that needs to know if `props` is a cursor, and would like to be able to use the custom defined `isCursor` to do it.

**Comment by torgeir** [comment]
It moved to [shouldupdate.js](]https://github.com/omniscientjs/omniscient/blob/master/shouldupdate.js#L19)

**Comment by phated** [comment]
@torgeir correct, but it may be changed when using `withDefaults`, which is why I am suggesting it be attached to ComponentCreator again

**Comment by mikaelbr** [comment]
You are thinking it's too verbose / mystic that you need to do something like:

```js
var localComponent = component.withDefaults({
  isCursor: function (potential) {
    // something something
   return component.shouldComponentUpdate.isCursor(potential);
  }
});
```

instead of 
```js
var localComponent = component.withDefaults({
  isCursor: function (potential) {
    // something something
   return component.isCursor(potential);
  }
});
```

But one can also override the internals of `shouldComponentUpdate` through component, like:
```js
var localComponent = component.withDefaults({
  // Override isEqualState in shouldComponentUpdate
  isEqualState: function (state, nextState) {
    // something something
   return component.shouldComponentUpdate.isEqualState(potential);
  }
});
```

So in a sense, we've grouped all internals on one place.

**Comment by phated** [comment]
Oh, okay.  I didn't dig deep enough to see those methods on `component.shouldComponentUpdate`.  Sorry for the issue. Closing.

**Comment by mikaelbr** [comment]
No worries, happy to get issues.
