### ISSUE TITLE
Example of using omniscient with react+immutable is incorrect

### ISSUE THREAD

**Issue by Gozala** [omniscientjs/omniscient#54]
When I first looked into omniscient I read following guide http://omniscientjs.github.io/guide.html#omniscient-react-js which unfortunately is invalid at least with a most recent version of immutable.js 

I think we should:

1. Update guide so that copy & pasting it will just work with recent versions of libraries mentioned.
2. Illustrate how immutable.js cursors can be used to create a render loop.

**Comment by torgeir** [comment]
We're in the progress of porting the site to jekyll, so expect an overhaul, but feel free to pr stuff that's easily fixable

**Comment by torgeir** [comment]
We're over on jekyll, so both writing stuff and accepting contributions will be easier

https://github.com/omniscientjs/omniscientjs.github.io

Some stuff probably still needs updating though

**Comment by mikaelbr** [comment]
Yeah, I just moved over to the platform, but some style changes is required, all documentation needs to be revised and i think we need to move over to generating api reference automatically based on jsdoc or something

**Comment by torgeir** [comment]
I did some work yesterday on making code samples runnable one web site! Added two simple examples to the front page, one slightly more advanced showing how to do a render loop. We can easily add more of the runnable stuff across the other articles as well
