### ISSUE TITLE
Tasks for documentation and new site

### ISSUE THREAD

**Issue by mikaelbr** [omniscientjs/omniscient#56]
Some tasks involved with the documentation and the new site:

- [x] Update documentation to cover Omniscient 3.0.0
- [x] Move over to jsdoc API Reference (or any alternatives)
- [x] Add immstruct API section to site
- [x] Revise color scheme (dark background?)
- [x] Change order of result/code view for playground and live code blocks
- [x] Revise header: Make it work better on mobile (responsive), scroll fixed on homepage.
- [x] Better Github link - Part of header?
- [x] Add predefined example list for playground
- [x] Revise existing guides and tutorials.

## Feedback

- [ ] Add notes on multiple cursors as input
- [ ] Add notes on potential drawbacks
- [ ] Migrate some of the README information to the homepage

## Guides
- [x] Fixe guide as per #54 
- [ ] Add immstruct guides and examples to guides.
- [ ] Add guide: Using Omniscient with Remote data
- [ ] Add guide: Using Omniscient with flux-like stores (comment that it's not necessary in most cases?)
- [ ] Add guide: Reference Cursors. What are they, how do you use them?
- [ ] Add guide: Immutable cursors (extended info in addition to https://github.com/omniscientjs/immstruct#usage)

Suggestions for more? Tutorials?

**Comment by Dashed** [comment]
I might be open to writing something on stale cursors to build a case for immstruct / reference cursors. It might be a little technical, but could provide insights on using cursors with react.

**Comment by Dashed** [comment]
I personally like the presentation of the concepts of raft (consensus algorithm equivalent to paxos): http://thesecretlivesofdata.com/raft/

Plus, the gold standard in introducing React: http://jlongster.com/Removing-User-Interface-Complexity,-or-Why-React-is-Awesome

------

Maybe the tutorial-like presentation of concepts in the above links can be incorporated into the article selling the case for top-down data flow: http://omniscientjs.github.io/guides/01-simpler-ui-reasoning-with-unidirectional/

This would raise better awareness of omniscient/immstruct, and put them above other immutable state management libraries.

**Comment by mikaelbr** [comment]
> I might be open to writing something on stale cursors to build a case for immstruct / reference cursors. It might be a little technical, but could provide insights on using cursors with react.

That would be great! The more guides and articles we can get, the better. I like the kind of articles which explains the concept and improves understanding, instead of just "learning the code". Technical is fine, we can have different degrees of difficulty on guides.

**Comment by torgeir** [comment]
Swapped code and results for the examples, and made more space for results in the playground so not compiling code doesnt make everything jump up and down as you type

**Comment by mikaelbr** [comment]
Updated the README to have correct syntax.

**Comment by Dashed** [comment]
`Edit On GitHub` links on top right corner are broken.
