### ISSUE TITLE
New Logo

### ISSUE THREAD

**Issue by mikaelbr** [omniscientjs/omniscient#57]
Should we change logo? Maybe we should look into having a prettier, cleaner logo. Maybe something with color (but could also work in black and white).

Inspiration suggestion from @Dashed : http://thenounproject.com/term/eye-of-providence/43465/

**Comment by Dashed** [comment]
I like this one, since it seems simpler: http://thenounproject.com/term/eye-of-providence/43465/

To me it looks like an eye on a "component tree" :smile: 

The SVG is in public domain, so I'm just dumping random colours onto individual vector pieces.

![](http://i.imgur.com/eJv1I18.png)

**Comment by Dashed** [comment]
Logo context: https://en.wikipedia.org/wiki/Eye_of_Providence

> The Eye of Providence (or the all-seeing eye of God) is a symbol showing an eye often surrounded by rays of light or a glory and usually enclosed by a triangle. It is sometimes interpreted as representing the eye of God watching over humankind (or divine providence).

**Comment by Gozala** [comment]
I like new logo, but I prefer single color one.

**Comment by mikaelbr** [comment]
I tried various logos based on the suggestion by @Dashed . I thought I was getting somewhere, but it all fell apart and in the end I just felt I was being stared at.

I really don't know if there are any of these that are usable.

![logos](https://cloud.githubusercontent.com/assets/606374/6276290/0875dcd0-b886-11e4-95a7-743ddfbe3c0f.png)

**Comment by Gozala** [comment]
I personally like 1:4 && 4:4 other seem to have very little white space that makes them almost blend with the triangle.

**Comment by Dashed** [comment]
I like 4th of logo 1.

> I thought I was getting somewhere, but it all fell apart and in the end I just felt I was being stared at.

:laughing:

**Comment by Dashed** [comment]
Have you tried joining the outlines of the triangle with the eye, but at the same time keeping the triangle hollow?

**Comment by torgeir** [comment]
> I thought I was getting somewhere, but it all fell apart and in the end I just felt I was being stared at.

Good one! :laughing: 

I'm also leaning towards 1:4

**Comment by mikaelbr** [comment]
We also have to take into consideration our existing logo. Or is it a consensus that this new concept is overall better than the original logo?

**Comment by Dashed** [comment]
I don't think it's a drastic change relative to the current logo.

Do you still want to preserve the "eye globe"?

**Comment by mikaelbr** [comment]
No need for me to preserve the globe. Initially I just thought it was a fun concept for "omniscient view".

**Comment by nbostrom** [comment]
I like the globe!

Something like this maybe? (Pretty similar to the original):

![omni2](https://cloud.githubusercontent.com/assets/588215/6444369/754d6718-c0fd-11e4-9887-92ad5ff54134.png)
![omni1](https://cloud.githubusercontent.com/assets/588215/6444371/78397b4c-c0fd-11e4-9594-ada0d681b26c.png)

**Comment by mikaelbr** [comment]
I like this. Looked cool with the "OMNISCIENT" text as well. I don't think there would be need for the ".JS" though. I liked the font.

**Comment by nbostrom** [comment]
Thanks! The only problem I have with it atm is that it that the height vs width dimensions make it look weird on its own (without the text). I will try to make it feel more circular or something.

**Comment by Dashed** [comment]
@nbostrom That looks awesome! Is there still room for the triangle for symbolic gesture to the eye of providence? :smile:

**Comment by nbostrom** [comment]
I played around with the triangles a lot. I noticed though that every time I got rid of the triangle the logo always looked a bit better. The triangle feels imbalanced in a way. I get the importance of the eye of providence though, so I will give it another shot.

**Comment by nbostrom** [comment]
The font is http://fontzone.net/font-details/aharoni-bold. I noticed that it went away from Google Fonts though. Maybe because of licensing issues.

**Comment by Dashed** [comment]
@nbostrom Out of curiosity, have you tried other colours? I'm wondering how purple would look.

**Comment by nbostrom** [comment]
@Dashed No, I haven't. I used variants of the colors in the current website. I can play around with other colors (including purple) if you like.

**Comment by mikaelbr** [comment]
I couldn't find any information and license for the font, just a Microsoft Font from 1993 with the same name. But I do like the font though.

**Comment by nbostrom** [comment]
I guess that I have had it installed for a while. ;)
Maybe we should to look for a similar one with an open license.

**Comment by mikaelbr** [comment]
@nbostrom I think you have based your color scheme on the old website, am I right? Maybe see the new colors on http://omniscientjs.github.io/

**Comment by mikaelbr** [comment]
@nbostrom And do you have svg file of the logo?

**Comment by nbostrom** [comment]
@mikaelbr I didn't actually use any exact color. I just picked a blue that looked good. That work remains. Yeah, I have svg files. They require some cleaning though.

**Comment by mikaelbr** [comment]
Would be great to get the source file and maybe switch out the old logo.

**Comment by nbostrom** [comment]
I'll see to it! I'm at work right now, and I am having quite a tight schedule. I hope to get time for this tonight :)

**Comment by mikaelbr** [comment]
Sure. No worries. No hurry. Just checking status. :+1:

**Comment by knowassociates** [comment]
A few of the engineers at our studio have been pretty excited about Omniscient and suggested I take a look at the logo/identity if I had some time. Had hoped to share some concepts with you earlier, but I've been working on a deadline for a client project.

Below are a few takes on the Omniscient logo that explore some themes including the Eye of Providence, but overall I've tried to emphasize simplicity, ease, and clarity while downplaying the illuminati imagery.

![omniscient_logoidentity-01](https://cloud.githubusercontent.com/assets/11195831/6563167/58f255a6-c675-11e4-9813-1b74f67410b7.png)
![omniscient_logoidentity-02](https://cloud.githubusercontent.com/assets/11195831/6563172/61322066-c675-11e4-83c9-ef5fb10c4bb6.png)
![omniscient_logoidentity-03](https://cloud.githubusercontent.com/assets/11195831/6563175/67de2afe-c675-11e4-80b3-2eaf4c9d59a6.png)
![omniscient_logoidentity-04](https://cloud.githubusercontent.com/assets/11195831/6563177/6bca19f2-c675-11e4-8499-e58d834930b6.png)
![omniscient_logoidentity-05](https://cloud.githubusercontent.com/assets/11195831/6563179/6fdeec0c-c675-11e4-8d10-328b9a2a416d.png)

**Comment by mikaelbr** [comment]
@knowassociates Very cool and thanks for your help! Neat to see different takes on the logo an completely different concepts. My favourite of the bunch is 04. Something entirely different, but with the hint of the eye of providence in the center (pyramid). The cool thing about that is that you can use it in different shades (gray, black/white) and still have the identity.

Maybe it kind of looks like it has "data flowing" in multiple directions, and Omniscient is about top-down data flow, but maybe I'm overthinking this.

**Comment by cmwelsh** [comment]
4 looks the most similar to the React logo, which I think is a good thing.

**Comment by nbostrom** [comment]
I also really like 04. It probably needs some more contrast though. Looked at it with a bad TN panel and could barely see it.

**Comment by nbostrom** [comment]
Another take:
![omni2](https://cloud.githubusercontent.com/assets/588215/6565116/094e0ae8-c6ae-11e4-9132-a4d10c033966.png)

**Comment by Dashed** [comment]
@knowassociates Those look awesome! I'm a big fan of 01 and 02.

I didn't notice the triangle shaped hole in the center of 04 until @mikaelbr pointed it out.

**Comment by knowassociates** [comment]
@mikaelbr Thanks. Glad you like the work.
In considering the audience for omniscient, and thinking of the things people will build with it a logo with fresh/positive tone feels like the right direction. I agree that the color on 4 may be a bit too subtle, can address that if you would like to move ahead with it.

I'll let things sit here for a bit and see if people gravitate towards one or the other. I can create assets and a simple style kit from any one of these if something rises to the top.

@nbostrom I like the scale of combined triangle + eye. The globe may be just one too many things going on. Maybe hint at it a bit with color but remove the continent forms?

@Dashed Thanks too. #1 is the weirdest in a way, and I like that. #2 feels a little generic in the static form, but could become interesting as a generative piece with some subtle animation.

side note: triangle logos are pretty much the best thing. I think we can all agree on that.

**Comment by nbostrom** [comment]
@knowassociates yeah, I agree. It's a bit messy. Personally I like my previous suggestion more than the last one.  ;) Maybe the continents could be dimmed down or something. As I said earlier, I really like your 04, but the gray is a little bit too light right now. It's hardly noticable on bad TN panels. It's very clear on this IPS panel though, but I don't think that IPS is the common case. If you improve the contrast you got my vote. :)

**Comment by mikaelbr** [comment]
I agree with @nbostrom . Some more contrast would do good for 04.

I also like @nbostrom's initial suggestion better than the new one, but I think that 04 can have more of a "identity" tied to it. More easily recognisable in different settings and shapes/colours.

https://github.com/omniscientjs/omniscient/issues/57#issuecomment-77950160 isn't too bad either, but there is a lot going on - and I get kind of a space-y / Star Trek-y wibe from it, for some reason.

**Comment by nbostrom** [comment]
@mikaelbr , yeah, either Star Trek or "maker of winter jackets"

**Comment by Dashed** [comment]
Or some evil corporation. :smiling_imp:

**Comment by DeepAnchor** [comment]
Hi, just noticed this thread and thought I'd give my 2c. 

I like the general shape of logo #1 (particularly 3:4) that @mikaelbr  posted, although it seems to be lacking in balance... or something. With its triangular shape, it's quite distinctive as far as logos go and as @Dashed has mentioned, its symbolism ties in quite nicely with how this project works. "Eye" logos by themselves are pretty generic IMO. 

As far as @knowassociates 's logos go, I like the design of the first one. It's clean and simple which matches the philosophy of this project. Also, the eye to triangle ratio seems nicely balanced here. However (and this may be just my personal preference here), giving the eye a color makes it too lively and personable. I'd prefer a black and white motif or at least colors that evoke more neutral or impassive feelings (like the eye of an omniscient deity would be :grinning:).

Personally I'd do away with the globe altogether as it's visually confusing IMO, thought I really like the font-face that was used.

**Comment by torgeir** [comment]
Awesome! Gotta love open source - nice work @nbostrom and @knowassociates! :tada: 

> I also like @nbostrom's initial suggestion better than the new one

Me too, the first of the two! Also, the font is nice.

For @knowassociates suggestions I lean towards 4! But I'd also like a little less subtle colors. It reminds me of something, but I'm unsure of what :) I'm also curious to what it would look like in a single color, e.g. white on the omniscient blue.

(In fact I also kind of like 3, but the eye feels a little squashed?)

**Comment by ArnoBuschmann** [comment]
I'd say, @nbostrom s 2nd suggestion is an extremely smart way to integrate the triangle, well done!

But actually I like his first one without triangle way better. Also note, that the triangle one takes more height when scaling. Less height is often of advantage, think about banners for example, which have a lot width but not much height.

Concerning JS or not, I like the JS version, it's cool to know the language right away and not having to check, if it is, for example, a closure library ;)

**Comment by Srdjan** [comment]
I like really @nbostrom 2nd suggestion - it has potential :)
here is a little twist to it:
![untitled](https://cloud.githubusercontent.com/assets/61190/6670974/70a81e70-cbd8-11e4-95d5-f69658cb11e0.png)

**Comment by knowassociates** [comment]
Had some time to make refinements to the #04 with color adjusted for greater legibility shown on Light/Dark background and a Black version shown to for clarity.

![omniscient_logoidentity02-color-a](https://cloud.githubusercontent.com/assets/11195831/6989481/dc7a715c-da29-11e4-8ad1-471f9502ac3e.png)
![omniscient_logoidentity02-color-b](https://cloud.githubusercontent.com/assets/11195831/6989483/de79c714-da29-11e4-819e-95c388c0b0b7.png)
![omniscient_logoidentity02-color-c](https://cloud.githubusercontent.com/assets/11195831/6989485/e2c164da-da29-11e4-9f15-2f9860fdce29.png)

@mikaelbr let me know if you'd like working files and some color specs to work from.

**Comment by Dashed** [comment]
@knowassociates Looks awesome!

I'm wondering if the 'O' in Omniscient should be capitalized or not.

**Comment by jeffbski** [comment]
@knowassociates great work! I love the look and evolution of these. very nice. You have some very talented designers on your team.

@Dashed I think that since the project takes ideas and inspiration from the Om project, that it is appropriate to capitalize it like Om does. That might help the mind connect the two patterns more easily since you can see that in the name. Otherwise I would agree with you, many projects have went to all lowercase.

**Comment by nbostrom** [comment]
@knowassociates that's awesome! You've got my vote.

**Comment by torgeir** [comment]
Damn, that's nice! Love it. :smile:

**Comment by mikaelbr** [comment]
@knowassociates That looks really good. I think the shape is really recognizable as a identity. You can send working files and color specs to my mail: mikaelbre@gmail.com

**Comment by mikaelbr** [comment]
For closure, new logo:

![omniscient_color-dark](https://cloud.githubusercontent.com/assets/606374/7154026/f14dbe5a-e351-11e4-8692-c641286dd9f5.png)


Full identity received from @knowassociates . Will update the homepage with usable logos and credits soon.

Thanks to all for their contribution and great discussion! :tada:
