### ISSUE TITLE
3.0.0 has outdated dist in npm

### ISSUE THREAD

**Issue by Gozala** [omniscientjs/omniscient#59]

**Comment by mikaelbr** [comment]
Oh, you're right, I've messed up and didnt push the dists. I updated this now, but this will cause an error on the cdn, so I need to do a patch release and set 3.0.0 as deprecated and wait for the cdn to update. I'll do this first thing in the morning.

**Comment by mikaelbr** [comment]
Fixed. Good thing this happened. Was worried we would't have to publish the obligatory vx.0.1 release. Thanks for letting us know!

Changelog: https://github.com/omniscientjs/omniscient/releases/tag/v3.0.1
