### ISSUE TITLE
require('omniscient').cached

### ISSUE THREAD

**Issue by Gozala** [omniscientjs/omniscient#64]
After using omniscient for some time now, we often runt into scenario like this one:
https://github.com/mozilla/browser.html/blob/master/src/browser/browser.js#L118

Here is a simplified version of it that is vaguely  based on code from the tutorial (although
here component takes two cursors one for `libs` and the other for `search`):

```js
var Matches = component('Matches', ({libs, search}) => {
  // Create a query out of the cursor
  var q = makeQuery(search);

  // Get all javascript projects that matches the query
  var matches = libs.map(function (lib) {
    return q.test(lib.get('title')) || q.test(lib.get('url'));
  });

  // Present the matches
  return React.DOM.ul({}, matches.toArray().map(function (lib, i) {
    return Match('match-' + lib.get('title'), lib);
  }));
});
```

Let's assume that unlike in original example `search` here is a cursor to some kind of object, let's say `{input: "*.js"}` rather than just string.

It would be really nice if `makeQuery` could be defined as follows:

```js
const {cached} = require('omniscient');
const makeQuery = cached(input => new RegExp(input.replace(/\*/, '[\\s\\S]*')));
```

Where implementation of `cached` could be something along this lines:

```js
const {shouldComponentUpdate} = require('omniscient');
const cached = f => {
  const g = input =>
    shouldComponentUpdate(input, g.input) ? g.return = f(input) : g.return

  return g
}
```

Which can be thought as a generalisation of `component` if we ignore all the react specifics it currently
does.

**Comment by torgeir** [comment]
this is a sound suggestion, and something like this would be useful, as our content focus implicitly suggests more stuff is moved into the render method executed on each render

**Comment by mikaelbr** [comment]
I'm hesitant to put this in the Omniscient core. Yes, it might be a handy util to have, but I don't necessarily think this is a core feature.

@torgeir and me discussed some, what to do, and I think we concluded in extending the `omniscient-mixins` repo to be `omniscient-utils` (or something in that manner) and having `require('omniscient-utils/mixins/*')` and `require('omniscient-utils/tools/*')` etc.

**Comment by Gozala** [comment]
@mikaelbr @torgeir I don't mind writing my own function to do that it's just I find omniscient's approach little confusing & misleading. On one hand it advocates pure functional approach (which is why I found it attractive) with it's pure `state -> dom` render function, but on the other hand if you need to handle any kind of user interaction current answer is use mixings with mutable `this.props`.

I really wish omniscient would provide a complete solution.

BTW my use of omniscient is pure render functions, so in my case`cached(renderComponent)` won't be different from `component(renderComponent)`.

**Comment by Gozala** [comment]
I can work on this if that's fine with everyone.
