### ISSUE TITLE
Alias `statics` with a better name and deprecate `statics`.

### ISSUE THREAD

**Issue by Gozala** [omniscientjs/omniscient#69]

**Comment by torgeir** [comment]
Suggestions welcome!

**Comment by torgeir** [comment]
Its intention is passing down stuff to components that does not trigger render. We don't like `statics` because it
- conflates React statics
- will also in time hold event handlers
- most likely doesnt hold static information

**Comment by mikaelbr** [comment]
Yeah. What's the best name to use? Most descriptive and concise.

Way forward:
- Add new property (with a descriptive name) as replacement for statics.
- Replace `statics` definition with a `Object.defineProperty` which points to the replacement both for set and get, but in addition to returning the value show a deprecation notice (`console.warn`)

These warnings should probably not be shown in production dist (minified).

**Comment by Gozala** [comment]
I have made few comments in #68 in regards to how I personally see `statics` or what they should be used for, so I'd like to post them here as well:

>> The point of statics (atleast initially), was to be a free haven for props and objects. A bucket where you can pass on data without re-rendering. I think if it sometimes causes a re-render, that would be unexpected?

> I guess it really depends on user expectations, so my take on this is following:

> Imagine I've invoked `View({ cursor }, { something })` then later on something has changed and we invoked `View({ cursor }, { something, yetAnotherThing })` my expectation would be that after second execution of `View` it's code would be able to make use of `statics.yetAnotherThing`, but in practice it won't be a case.

> While it does really depends what we tell users they should use `statics` for, I still think it will be surprising if whatever was passed won't be there when attempted to use it.

> To me `statics` are basically a solution to get away from `this.props` although I think their behavior should pretty much match it. What I mean here is that even if `shouldComponentUpdate` returns `false` in component `this.props` still get updated to whatever was passed in. I expect same from `statics` with minor caveat that `shouldComponentUpdate` will return `false` no matter what have being passed in statics.

> So ideally we would just mutate `statics` such that for user it will be transparent, but problem there is that users could stored references for `static.someThing` in which case our mutations will no longer be transparent. This patch actually does cover case where `statics.someThing` is a function, but what if in subsequent calls it is no longer a function, or if it was not a function in first place ? In those cases I believe behavior will be surprising (or maybe not, I guess depends on expectation) at least to me.

> That being said I don't think passing anything but event handlers through statics is a good idea (partially because of the destroyed referential transparency in those cases) and I don't intend to, but then I think unless we re-trigger render to keep referential transparency we need to clearly explain how statics will behave and what users should be using them for.


> I think I did not made it fully clear, the reason I suggested to re-trigger render if type signature of `statics` has change was so that we would have a referential transparency and as far as user is concerned there should not be observable difference in whether render was re-triggered or not.

> On the other hand checking type signatures won't resolve issue for `var something = statics.something` if `something` is an object that has being swapped, but I think it at least reduced a surface for surprise.

**Comment by Gozala** [comment]
More I think about it more I feel that what would most sense is to treat first argument to a component as a data to be rendered, while second argument a.k.a `statics` is basically a way for component to communicate events a.k.a "side effects" back (in cases where cursors aren't used, or when handling of side effects should be delegated). So maybe we should propose that `statics` be used for exactly that purpose and serve as a container for passing over event handlers, CSP channels, FRP signals, event emitters or whatever other communication channels maybe adequate.

If we put it that that way, I think it's also becomes more clear why changes to statics don't trigger render, because input being rendered has not changed, just a communication pipe got rerouted so we can do it behind the scenes.

**Comment by mikaelbr** [comment]
I think these values are the type of values you'd want to use with "`statics`":
 - channels (csp-esque things)
 - signals / properties / event streams (frp constructions) 
 - event emitters
 - event handlers

And I don't think there's much else you'd want to pass. There should be clear guidelines for that you shouldn't have anything altering the output in `statics`, that would break referential transparency and thus is an anti-pattern.

**Comment by mikaelbr** [comment]
I think in this case, @Gozala, we very much agree. See my comments both https://github.com/omniscientjs/omniscient/issues/69#issuecomment-76285775 and https://github.com/omniscientjs/omniscient/pull/68#issuecomment-76285101 where I actually say all the things you mention as well :+1: 

And this has actually, more or less, been the "envision" of statics. Provide a way to "talk back to your parents".

**Comment by Gozala** [comment]
In that case maybe it could be called `out` or `output` or `pipe` ?

**Comment by torgeir** [comment]
> More I think about it more I feel that what would most sense is to treat first argument to a component as a data to be rendered, while second argument a.k.a statics is basically a way for component to communicate events a.k.a "side effects" back (in cases where cursors aren't used, or when handling of side effects should be delegated). So maybe we should propose that statics be used for exactly that (..)

That is indeed exactly what we intended for it :smile:

**Comment by Gozala** [comment]
I just had this other idea, what if we don't give it any new name but just treat it as a second argument ? So that it would be always used like:

```js
var view = component((input, output) => {
});

view({cursor}, {onChange});
```

Which will be syntactic sugar for:

```js
view({cursor, [component.shouldNotUpdate]: {onChange}})
```

Don't know how that's going to work in jsx case though.

**Comment by mikaelbr** [comment]
> I just had this other idea, what if we don't give it any new name but just treat it as a second argument ? So that it would be always used like:
> ```js
var view = component((input, output) => {
});

>view({cursor}, {onChange});
>```

This is how it works now. 

>  Which will be syntactic sugar for:
> ```js
> view({cursor, [component.shouldNotUpdate]: {onChange}})
> ```

So rename from `statics` to a variable in  `component.shouldNotUpdate`? 


> Don't know how that's going to work in jsx case though

I think to simplify this, wed have to just use the convention of using the value of `component.shouldNotUpdate` instead of having it as a variable. This way it would work the same as with non-jsx. Same as the existing behaviour, but renaming `statics` to be more descriptive.

**Comment by Gozala** [comment]
> think to simplify this, wed have to just use the convention of using the value of component.shouldNotUpdate instead of having it as a variable. This way it would work the same as with non-jsx. Same as the existing behaviour, but renaming statics to be more descriptive.

I'm not sure I follow, do you suggest we do what I proposed in #76 (referring to boxing values that should not affect `shouldComponentUpdate` checks ?

If so I really like how all pieces start to fit together to form what I think very obvious API. This and some work on `cached` got me thinking about yet another idea. What if `component` acted pretty much the same as `cached` does what I mean is what if instead of treating some arguments specially and others not we would just treat `arguments` as `props` & used that boxing technique to pass objects that we don't wish to be checked by `shouldComponentUpdate`. What that will give us would be something along this lines:

```js
var Tab = component((key, uri, progressCursor, onChange) => {
  return DOM.div({ ... }, .....);
})
```

Note that `cached` does pretty much the same only difference will be that result of this will be a React component while result of `cached` is just a function.

That being said I have no idea how that is going to play with jsx.

**Comment by Gozala** [comment]
Another thing that I like about that idea is that there will be no need to do a deep check of props just comparing elements would be enough, since grouping cursors is gonna be easy.

**Comment by andrewluetgers** [comment]
I'm curious about the prospect of using statics to get more fine grained control of rendering. Currently you have a situation where all the parents need to render when any of their children states change. I'm curious about passing cursors via statics to do this. Obviously there would be more to it than that, but statics seem a reasonable way to pass along state that should not trigger the parent to render but will be provided to and used by the child.

**Comment by jeffbski** [comment]
If you want to pass things down to children without having all the intermediate children needing to deal with it, you can use higher order components or pass through childContext.

 - https://gist.github.com/sebmarkbage/ef0bf1f338a7182b6775 higher order components - similar to mixing in but by composing classes

 - https://www.tildedave.com/2014/11/15/introduction-to-contexts-in-react-js.html you would use getChildContext to make context available to descendants.

**Comment by andrewluetgers** [comment]
@jeffbski thanks for the advice take a look at https://github.com/omniscientjs/omniscient/issues/93 to see what I came up with

**Comment by mikaelbr** [comment]
This will be changed in #116. `statics` is gone, and [`ignore`](https://github.com/omniscientjs/omnipotent#ignorefields--stringarraystring-component--component) is the new thing.
