### ISSUE TITLE
Child to parent communication via cursors

### ISSUE THREAD

**Issue by Gozala** [omniscientjs/omniscient#71]
This is vaguely related to #67, as I was trying to find a solution for a child to cause side on a state that does is not part of state that affects it's output. In other words originally, I would pass parent components state along with a child state so that child could render itself, but then make changes to parent like remove itself for example. The problem with that approach was that any time parent would change all it's children would be re-triggered since parent state was passed to each one.

So then I considered using CSP channels to do communication, but then problem with those has being that one needs to create & subscribe to them and that means you no longer can use plain `component(render)` style, not to mention that it seems overkill for just removing a child from it's parent.

I think #67 provides a simple solution, although it does kind of require wrapping actual operational functions in event handlers to be passed down to children. In that regard just passing down a parent cursors seems more appealing.

Lately I have being thinking that if cursors just a had a way to access it's parent that could provide pretty elegant solution for children to cause changes upwards.

**Comment by Gozala** [comment]
Although it would imply that children would have to have a knowledge about the structure of data above them which introduces unfortunate coupling.

**Comment by Gozala** [comment]
I have being digging into how om's cursor stuff & it looks like they do have an api to access part cursor by calling `(root-cursor cursor)`:

https://github.com/omcljs/om/wiki/Cursors#accessing-cursors

I wonder if we could something along those lines, only problem is though that access parent cursor will likely give you out of date cursor and changes to it will likely case same problems as described in #67 as let's say if it's a cursor for `collection` actual collection may have different number of items or even have them reordered.

**Comment by mikaelbr** [comment]
I really feel like being able to communicate with parents through cursors can too easily be misused. I don't want to encourage anti-patterns. I think limiting the "back communication" to the previously mentioned constructs is for the best.

**Comment by gilbox** [comment]
Why not use flux to solve this?

**Comment by Gozala** [comment]
> I really feel like being able to communicate with parents through cursors can too easily be misused. I don't want to encourage anti-patterns. I think limiting the "back communication" to the previously mentioned constructs is for the best.

I think communication is an awkward word, what it's really about is updating part of state that are not affects result of render.

I think reference cursors are kind good fit for that actually. I mainly started this thread to explore how om happens to solve that issue.

**Comment by Gozala** [comment]
> Why not use flux to solve this?

That assumes that flux is a best solution for (any) problem, which I don't believe is the case. Also there are cases where non  "flux" is used to solve the same problems.

http://elm-lang.org/blog/Blazing-Fast-Html.elm
https://github.com/omcljs/om


In other words I don't think having one solution is a reason not to explore others.

**Comment by mikaelbr** [comment]
> Why not use flux to solve this?

Not everyone use the flux architecture, and that is something we want to support. In many cases flux can be somewhat verbose and with a lot of overhead - and simply not a good choice. In other cases some of the approaches can be a better fit, and you can do something similar with actions and using immstruct like a "store". 

> I think reference cursors are kind good fit for that actually. I mainly started this thread to explore how om happens to solve that issue.

Yeah, reference cursors would be a good fit for this. Would be the same as the updating event handlers.

**Comment by mikaelbr** [comment]
I feel this discussion is outdated. Closing the issue. Feel free to comment if anything arises.
