### ISSUE TITLE
Relax peer dependency for latest React.js versions

### ISSUE THREAD

**Issue by jeffbski** [omniscientjs/omniscient#72]
Now that there are new React.js 0.13 versions, we should relax the peer dependency in package.json so they can be used. I'm not sure the easiest syntax for doing this (rather than listing a bunch of beta versions).

npm view react
```
    '0.13.0-beta.1': '2015-01-28T05:19:01.230Z',
     '0.13.0-beta.2': '2015-02-14T02:37:43.316Z',
     '0.13.0-rc1': '2015-02-22T21:36:01.461Z' },
```

Currently package.json has

```
"peerDependencies": {
    "react": ">=0.12.0 || 0.13.0-beta.1"
  },
```

so npm won't let me use the latest React RC without hacking it.

**Comment by mikaelbr** [comment]
Fixed in #74
