### ISSUE TITLE
We should validate statics to make users aware if they misuse them.

### ISSUE THREAD

**Issue by Gozala** [omniscientjs/omniscient#75]
Here is a related conversation from gitter:
https://gitter.im/omniscientjs/omniscient?at=54f02b645092f77b218b6180

Currently there is a subtle problem with the way statics work. For example consider following code

```js
View(input, {change});

// ....

View(input, {update});
```

Result of this code is that `View` will hold reference to outdated `statics`, meaning that there will be likely obsolete `change` and there will be no `update`. There is a high probability that `View` ended up in error state.

I would also argue that this is wrong use of statics, which is why I think omniscient should warn users about such misuse of them.

As discussed in other threads `statics` are there to allow component communicate upwards with a ancestors. As far as I understand logic here is that if communication pipeline got updated that is no reason to re-render component, instead we could rewire existing pipeline and there for net result will be as if component was re-rendered.

There is already a work in progress that takes care of rewiring event handlers (see #68), but now consider that `change` and `update` were event handlers, it becomes clear that there is no right way to rewire handlers & at best we could just give-up and re-render + warn users that their invalid use of statics defeated their purpose and caused render to be triggered.

Now I also think that `change` in this example could have being a CSP Channel or FRP Signal, or Event Emitter or maybe even a cursor. Either way I think omniscient should compare existing and new statics passed on `componentWillReceiveProps` and if it's unable to rewire existing pipeline it should warn a user about invalid use of `statics`.

I also think it's would be a good idea to cause a re-render when rewiring of pipeline can't be completed to avoid putting component into a broken state, but even if do not re-render we should warn users.

**Comment by Gozala** [comment]
I think another somewhat related subject would be how do we rewire things that aren't event handler functions ? Or do we even want to attempt to support other types ? If so what should we be supporting ? 

Maybe there could be some API that omniscient could request for messaging pipes to implement that it could use to rewire them ?

For the very least I think we could validate that keys and types of associated values match up & warn users if they do not, because at that point it's pretty clear that component will enter error state.

**Comment by Gozala** [comment]
Alternative take would be to delegate responsibility to a user, by requiring `statics` to be an object that implements `statics.transplant(newStatics)` and if it succeeds move on, if it does not `console.warn` and re-render.

That way users could implement their own types for rewiring channels, signals & what not.

**Comment by mikaelbr** [comment]
This is now outdated due to #116. Statics will now be a explicit choice, not implicit or "magic". Closing the issue, but feel free to continue the discussion if you feel like continuing the conversation.
