### ISSUE TITLE
this.props.cursor is undefined in mixin

### ISSUE THREAD

**Issue by adamschoenemann** [omniscientjs/omniscient#80]
While following the tutorial "01-editing-basic-tutorial-creating-list-with-live-filtering/", the mixin with the `changeHandler` function does not have the unboxed cursor. Instead, the cusor resides in `this.props.__singleCursor`

**Comment by torgeir** [comment]
I've also seen this in a mixin when accessing this.props directly

**Comment by mikaelbr** [comment]
Yeah, this is an unfortunate bug from when the automatic unwrapping was implemented. At the moment I don't really see how we can avoid this issue without having it be exposed to for instance `this.props._cursor` where `_cursor` is used as detection of a single cursor.

The above answer might be a bit technical and require you to have knowledge of how the internals work, for a more simpler answer see below:

To avoid this problem for now, you can override the `cursorField` option:

```js
var omniscient = require('omniscient');
var component = omniscient.withDefaults({
  cursorField: cursor
});

var MyComponent = component(function (cursor) {
  assert(this.props.cursor === cursor)
});

React.render(MyComponent(someCursor), document.body);
```

But note, this will cause unwrapping of JSX named cursors as well:

```jsx
var omniscient = require('omniscient');
var component = omniscient.withDefaults({
  cursorField: cursor
});

var MyComponent = component(function (cursor) {
  // passed argument is not props but unwrapped cursor
  assert(this.props.cursor === cursor)
});

React.render(<MyComponent cursor={someCursor} />, document.body);
```

Not a perfect workaround, but a temporary one until we find a better way to handle unwrapping/wrapping.

**Comment by Dashed** [comment]
You can do the following by being explicit of the cursor dependency:

```js
var mixins = {
  changeHandler: function (cursor) {
    return function changeHandler(e) {
        cursor.update(function (currentSearch) {
            return e.currentTarget.value;
        });
    }
  }
};

var SearchBox = component('SearchBox', mixins, function (cursor) {
  return React.DOM.div({}, d.input({
    placeholder: "Search..",
    value: cursor.deref(),
    onChange: this.changeHandler(cursor)
  }));
});
```

**Comment by mikaelbr** [comment]
@Dashed That's a way to do it if you prefer higher order functions to all. But also, if you think of components as pure (instead of just the functions), they can share "variables" across their mixins, just to separate some functionality. I think the best way here is to set `this.cursor` in case of wrapped/unwrapped cursor. It's kind of an gotcha, but it works as expected. So the previous example would be:

```js
var component = require('omniscient');

var MyComponent = component(function (cursor) {
  assert(this.cursor === cursor)
});

React.render(MyComponent(someCursor), document.body);
```

But when not unwrapping:
```js
var component = require('omniscient');

var MyComponent = component(function (cursor) {
  assert(this.props.cursor === cursor)
});

React.render(MyComponent({ cursor: someCursor }), document.body);
```

Is this something we can live with given proper documentation, or is it too unexpected? cc @torgeir
