### ISSUE TITLE
Issues with async rendering (requestAnimationFrame)

### ISSUE THREAD

**Issue by Gozala** [omniscientjs/omniscient#83]
We have being discussing [this on gitter](https://gitter.im/omniscientjs/omniscient?at=54f4ce638d79a4a8116b7325) so I though we should have a issue for this.

Short version is, if your render loop is not in sync with your update loop, you will run into issue like one illustrated here:

```js
ToggleButton({ onClick: event => cursor.set(‘isChecked’, !cursor.get(‘isChecked’))})
```

The issues you will run into is that no matter how many times you managed to click with in same render only single update will happen, so if you click twice button won't end up in the same state as it started with.

Solution that will do the job here are "reference cursors", but than it becomes little unclear when to use regular cursors and when to use "reference" cursors. There is also the fact that "reference cursors" can change under the hood & using them kind of puts you into same shoes as `this.props.isChecked`.

Om seems to do something different and interesting as described here:
https://github.com/omcljs/om/wiki/Cursors#accessing-cursors

It has `(defer cursor)` to access current state, so it will be like `.deref()` on reference cursor and it also has `(om/value cursor)` what will return rendered state, which is equivalent of `.deref()` on regular immutable.js cursor. Cool side effect of this is that there is no longer question which type of cursor should be used when. In addition during `render` om cursors act just like immutable.js data structures, which I believe prevents user from causing error state. I've run into that few times myself, if you try to update cursor in render function react will dump warning and will enter into semi broken state.

**Comment by Dashed** [comment]
Here is a demonstration of the issue: http://jsbin.com/ramibe/2/edit?js,console,output

**Comment by Dashed** [comment]
To elaborate. This is an issue when the render is tied to some event loop (animation frame, game loop, etc) instead of native JS event loop.

Multiple user events, which trigger associated event handlers, may occur prior to a render call. The issue is that event handlers may read values from a cursor and then update a cursor with those values.
Thus, all event handler calls after the first user event, do not use updated cursors (they became stale); due to the immutable nature of cursors. 

Reference cursors would solve this.

**Comment by mikaelbr** [comment]
> It has (defer cursor) to access current state, so it will be like .deref() on reference cursor and it also has (om/value cursor) what will return rendered state, which is equivalent of .deref() on regular immutable.js cursor. Cool side effect of this is that there is no longer question which type of cursor should be used when. In addition during render om cursors act just like immutable.js data structures, which I believe prevents user from causing error state. I've run into that few times myself, if you try to update cursor in render function react will dump warning and will enter into semi broken state.

So it would be like:

```js
// cursor = cursor to 1
cursor.update(_ => cursor.deref() + 1) // => 2
cursor.update(_ => cursor.deref() + 1) // => 3
cursor.update(_ => cursor.deref() + 1) // => 4
```

But you could also do:

```js
// cursor = cursor to 1
cursor.update(_ => cursor.value() + 1) // => 2
cursor.update(_ => cursor.value() + 1) // => 2
cursor.update(_ => cursor.value() + 1) // => 2
```

And that would also work on "internal" cursors:

```js
// cursor = cursor to 1
cursor.update(myCursor => myCursor.deref() + 1) // => 2
cursor.update(myCursor => myCursor.deref() + 1) // => 3
cursor.update(myCursor => myCursor.deref() + 1) // => 4
```

**Comment by guillaume86** [comment]
I'm just reading through the issues before giving this lib a try, so my expertise on the matter is very limited:

Shoudn't the event loop and the render loop be dissociated to simply solve that issue? 
The event loop would do the same that the current "render" loop, except it wouldn't need to compute diffs and apply them to the dom.

**Comment by mikaelbr** [comment]
I think reference cursors covers these sort of issues, as described above. Cursors them self are immutable, and this is a consequence of that. Reference cursors are made to have accessors to the latest cursors, to be able to solve these cases.
