### ISSUE TITLE
Some thought about dealing with mutable state in referentially transparent way

### ISSUE THREAD

**Issue by Gozala** [omniscientjs/omniscient#84]
So this thread had being triggered by some of the discussion on gitter related to #83. Here is my overall thoughts on current state of things:

1. Don't like reference cursors they don't seem any better than plain mutable state, although updates to it will trigger render which is nice, but overall not much different from `this.props` & `this.state`.
2. Having two different "immutable" and "reference" cursors is confusing not clear which one should be used & when. Maybe some documentation will help, but explaining this to others had being a challenge for me personally.
3. Maybe doing something like Om's cursors in https://github.com/omniscientjs/immstruct/issues/41#issuecomment-76831630 would make sense as it would at least resolve which kind of cursor to use question, although it still has things changed under the hood moment that I'm not very fond off. To be clear the fact that `cursor.deref()` can return different result based on time of invocation is what I find unfortunate.

Thinking and talking about it got me thinking about how this ideas be integrated without having side-effecty smell to them. So I came to this idea that is fusion of Om's cursors https://github.com/omcljs/om/wiki/Cursors#accessing-cursors and Elm's take on HTML http://elm-lang.org/blog/Blazing-Fast-Html.elm

Elm is purely functional so it needs to deal without observable side effects, although at this state I don't think it handlers separation of concerns that well. Anyway here is the idea:

```js
component(cursor =>
  // cursor in this context isn't immutable.js cursor it's just an immutable.js structure
  // with a keypath to the root stored on it, there for update & set does nothing but
  // genertaes new immutbale.js data structures. `get` and `getIn` also return immutable.js
  // data structures but further include `keypath`.
  ToggleButton({
    isChecked: cursor.get('isChecked'),
    // `action(change, cursor)` function can be used to create an event handler that
    // basically will do `cursor.update(change)` when invoked, althoug in this case
    // `state` will be current state of the cursor not the state that cursor had
    // when it was passed, which means that `cursor.get('isChecked') == state.get('isChecked')`
    // may or may not be `true`. Return value of the function action is created from will
    // be used to notify observers with an update, more simply new render step will be triggered.
    onClick: action(cursor, state => state.set('isChecked', !state.get('isChecked')))
  }));
```

What if cursors where not special & instead they were just same immutable.js data structures with little more context of their origin (meaning reference to root structure + key path). Of course we would need to cause side effects somehow which is I figured could be borrowed from elm. In elm instead of updating cursors or local state you create HTML node that can forward transformed events to designated signal this is how it looks like: https://github.com/evancz/elm-html/blob/master/examples/TextReverser.elm#L31

So had this idea what if same trick could be applied here, instead of changing anything define handlers that describe what changes they would like to perform and then let the system do them for us. That is what `action` does it takes a transformation function and a `cursor` it will be operating on. When event handler is invoked it will pass a transformation function current state for the `key path` that `cursor` originated from and will swap state under that `key path` with a result returned by transformation function. 

This may not look that much different, but cursor.get('isActive') will return same value regardless of when you call it. As of access to current state it's passed in to transformation function so no visible side effects like `cursor.deref()` changing based on time. As of side effects everything is handled by system / omniscient so end user API is totally pure and functional.

I don't know how much you guys care about it, but I thought I'd still share it.

**Comment by Gozala** [comment]
BTW I also expect `action(cursor, handler)` to return same function instance if `cursor` has same `keypath` and `root` (or derived `root`) and identical `handler`. That way they could be passed around without causing re-renders.

**Comment by Gozala** [comment]
One open ended question is how does one update state in two different places in one handler, which I don't have a good answer for. But one could be to allow grouping cursors like `structure.cursor({ foo: ['path', 'to', 'foo'], bar: ['path', 'to', 'bar'] })` where updates to `foo` and `bar` will be propagated to it's relevant paths.

**Comment by Dashed** [comment]
To me, `action(cursor, state => state.set('isChecked', !state.get('isChecked')))` looks a lot like reference cursor that is wrapped:

```js
function action(cursor, fn) {
    var ref = immstruct.reference(cursor);
    return function() {
        return fn(ref.cursor());
    };
}
```

I'm unsure how flexible this is supposed to be.

**Comment by Dashed** [comment]
I made a wrapper on immutable cursors: https://gist.github.com/Dashed/27c0d2a20d8e53e1447e

The feature I want to bring to attention is the `.refresh()` function which returns a "refreshed" cursor.

So problem would be alleviated in the following manner: 

```js
ToggleButton({ onClick: (event) => {
        const = !cursor.refresh().get(‘isChecked’);
        cursor.refresh().set(‘isChecked’, newVal);
    }
});
```

**Comment by Gozala** [comment]
@Dashed I have not realised it was possible to create reference cursor out of existing cursor, that is cool as that could be used to implement mentioned `action` as you showed.

Please note that my intent is to have a referentially transparent API which implies that calling same function with same input will always return same results, that is why I would not like to use reference cursors or `.refresh()` as is.

Described `action(...)` on the other hand alleviates the problem as result of function is never called by hand and even if it was it's pure intent is to cause side-effect by restarting a render flow. In other words cursor remains immutable while handler is just passed in the latest value as argument.

Unfortunately I quickly runt into limitations of that approach when I was playing around with that idea, to be specific one handler sometimes needs to update multiple things in the data structure, there for operation on multiple cursors will be required. So far I have being thinking something along this lines:

```js
var submitTask = function(state) {
  var id = state.getIn(['uid', 0]);
  var text = state.getIn(['field', 0]);
  var item = task(text, false, false, id);
  return state.updateIn(['uid', 0], inc).
              .updateIn(['field', 0], emptyString).
              .update('items', push(item));
}

action(submitTask, cursor({
  field: 'field',
  uid: 'uid',
  items: 'items'
});
```

But it starts to be more complicated than I intended, specially since it would be really hard to return same function from `action` when such a "virtual cursors" are created.

**Comment by Dashed** [comment]
I'm unsure if this is your flavour:

```js
cursor.record();

var id = cursor.getIn(['uid', 0]);
var text = cursor.getIn(['field', 0]);
var item = task(text, false, false, id);
cursor.updateIn(['uid', 0], inc)
          .updateIn(['field', 0], emptyString)
          .update('items', push(item));

cursor.stop();
```

**Comment by Gozala** [comment]
To be clear this is how I imagine something like `action` could be implemented:

```js
const action = (edit, cursor) => {
  const keyPath = Cursor.keyPath(cursor);
  const root = Cursor.root(cursor);
  
  const step = (to, from, path) => {
    const current = cursor.deref();
    // Note that only components that rely on state that changed
    // will be retriggered during rendering. This implies that some components
    // may be holding onto old cursors. If that is the case state `from` which
    // update was triggered won't match `current` state, there for we need to
    // be smart about handling updates.

    // If state update came `from` matches `current` state than component
    // triggering it was up to date & we just swap the current state to a
    // state it was updated `to`.
    if (current == from) {
      cursor = Cursor.from(to, step);
    } else {
      // Othewise update was triggered from component that skipped update(s)
      // there for we can't just swap `current` state, instead we should focus
      // on changes under the `path` that were updated and apply those to the
      // current `state`.

      // If path was removed & it does exist in current state we remove
      // it from current state.
      if (!to.hasIn(path) && current.hasIn(path)) {
        cursor = Cursor.from(current.removeIn(path), step);
      } else {
        // Otherwise we swap the state under the current path.
        cursor = Cursor.from(current.setIn(path, to.getIn(path)), step);
      }
    }
  };
  
  step(root, null, []);
  
  return (...params) =>
    cursor.updateIn(keyPath, state => edit(state, ...params))
};
```

**Comment by Dashed** [comment]
Related feature I toyed with: https://github.com/omniscientjs/immstruct/issues/25

**Comment by jeffbski** [comment]
@Gozala For me it makes sense to use normal cursors when want to pass things down through props to children. Efficient shouldComponentUpdate for everything down the tree. 

Then if I want to forgo doing that because I need to go deep in a tree and don't want to pass through all the intermediate components, I use a reference cursor. I pass it down from the top of my app using getChildContext, so it magically appears in the this.context where my component can use it without having to deal with it in the intermediate components. However since it did not come in through props, the component will not know when to update, so `this.setState({cursor: this.context.myRefCursor.cursor())})` and then setup observer to update state whenever rc changes `this.context.myRefCursor.observe(() => this.setState({cursor: this.context.myRefCursor.cursor()})`. My render function uses the cursor from state. Thus anytime the RC updates, it calls set state with the current cursor causing a render. The nice thing is that everything is still wrapped up in a global app state which can be observed and and also we can keep history for undo/redo.


So for me I like normal cursors for passing down through props and relying on efficient shouldComponentUpdate to render.

When I need to jump deep in a tree and don't want to pass down, I create a reference cursor that gets fed through getChildContext down to the children. I create a cursor off it and setState, then observe and update setState when changes.

Hoping that helps some?

**Comment by torgeir** [comment]
> For me it makes sense to use normal cursors when want to pass things down through props to children. Efficient shouldComponentUpdate for everything down the tree.
>
> Then if I want to forgo doing that because I need to go deep in a tree and don't want to pass through all the intermediate components, I use a reference cursor.

@jeffbski and that's pretty much what we aimed for! 

Didn't think of using child contexts, though, that's an alternative if you don't like components closing over your reference cursors. If your component does close over a reference cursor however, [something like this](https://github.com/omniscientjs/omniscient-mixins/blob/master/mixins/forceUpdateOn.js) might come in handy.

**Comment by mikaelbr** [comment]
This seams as something that can exist in a separate implementation. Closing this for now, but still an interesting thought.
