### ISSUE TITLE
singlecursor pass through for props hides cursor from mixin methods

### ISSUE THREAD

**Issue by doesnotexist** [omniscientjs/omniscient#88]
I've noticed that if the  singlecursor passed as props  is triggered, then you can't get at the cursor from a mixin.  So I am unable to get at this.props.get('propertyname') from inside a mixin method such as componentDidUpdate.

**Comment by mikaelbr** [comment]
Hi!

Already covered in #80 . Merged and will be updated in `v3.1.0` which is ready to publish. Will publish very soon.

**Comment by mikaelbr** [comment]
Published now.
