### ISSUE TITLE
RFC: new subcursor method `cursorAt(fullPath)` for Immutable-js/contrib/cursor

### ISSUE THREAD

**Issue by jeffbski** [omniscientjs/omniscient#90]
**Premise: Relative path cursors are difficult to reason about and become maintenance burden as a structure changes. Adding cursor.cursorAt(fullPath) which creates subcursor but using fullpath gives some of the benefits of reference cursors while still using a subcursor data flow.**

(I am posting this RFC here in Omniscient for discussion since this community really is looking into the best ways to do this, and I would like your opinions)

**I really like using cursors to feed data down to components.** They are straight forward and efficient to use in React. 

However **I dislike using relative paths to create cursors**. To determine what a cursor is pointing to, I need to look at the previous cursors all the way up concatenating them into a full path. 

Another issue is that **if a structure is reorganized over time**, searching out where to make these relative cursor path changes can be difficult. You can't simply look for a certain path, **since they are relative and you need to consider the parent**.

Contrast this with reference cursors which basically use an absolute full path. The cognitive load in figuring out what something points to is much easier, you don't have to consider the parents at all. The path is all you need. If you create these in one location, then whenever you want to change the app structure, just adjust the reference paths and you are done, no need to search through code or determine parents, etc.

So I was wondering if we could come up with a way to have **some of the advantages of absolute path reference cursors in regular cursors.**

**My idea is to create a new Cursor method `cursorAt` with the name implying that you will provide a full path rather than a relative path.** When you call cursorAt on an existing cursor it checks to see if the path you have asked for is a subpath of the current. If it is, then it creates a new cursor and returns it. If it isn't then it throws an Error so you can detect the issue quickly and fix your code.

Example using the `cursorAt(fullPathArray)` method to create a subcursor:
```javascript
var structure = Immutable.fromJS({
  storeProfile: {
    name: 'bar',
    zip: 1111
  },
  items: [
    { id: 1, name: 'foo' }
  ],
  storeMenu: {
    categories: {
      featured: [
        'abc',
        'def'
      ],
      major: [
        'cat',
        'dog'
      ]
    }
  }
});
var cs = Cursor.from(structure, [], function (newData, root, keyPath) {
  structure = newData;
});

// setup my absolute path arrays which I will use with cursorAt
// I am creating these arrays using split for convenience, but not required
var storeProfilePath = 'storeProfile'.split('.');
var itemsPath = 'items'.split('.');
var featuredCategoriesPath = 'storeMenu.categories.featured'.split('.');
var majorCategoriesPath = 'storeMenu.categories.major'.split('.');

var storeProfileCursor = cs.cursorAt(storeProfilePath); // { name: 'bar', zip: 1111 }
var featuredCategoriesCursor = cs.cursorAt(featuredCategoriesPath); // ['abc', 'def' ]

// the following will throw an error so we can fix our code if we
// try to create a cursor that isn't a child of the parent
// throws Error: Non-descendant cursor path:items parent:storeMenu,categories,featured
var wontWork = featuredCategoriesCursor.cursorAt(itemsPath);
```

For me this seems like a step forward since absolute paths are easy to reason about and I can still continue to use subcursors for the majority of my code. When the app structure changes, I just update my list of absolute paths which I can keep together to make it easy. If some reason I miss a path or the app structure changed such that data is no longer organized hierarchichly, when I run my code or tests, I will get an error indicating that my cursorAt won't work, and I can fix the code.

The code to add this to the immutable-js/contrib/cursor is pretty simple

```javascript
KeyedCursorPrototype.cursorAt =
IndexedCursorPrototype.cursorAt = function(keyPath) {
  keyPath = valToKeyPath(keyPath);
  // could check that keyPath equals existing and return this
  var cursor = makeCursor( // call without value
    this._rootData,
    keyPath,
    this._onChange
  );
  if (!arrayStartsWith(keyPath, this._keyPath)) {
    // cursor._nonDescendant = true;
    throw new Error('Non-descendant cursor path:' + keyPath +
                    ' parent:' + this._keyPath);
  }
  return cursor;
}

/**
  shallow array comparison, suitable for array of strings
  */
function arrayStartsWith(arr, arrStart) {
  if (arr.length < arrStart.length) { return false; }
  for(var i = 0; i<arrStart.length; i++) {
    if (arr[i] !== arrStart[i]) { return false; }
  }
  return true;
}
```

What do you think? Is this a step in the right direction or are there other ways to approach this?

**Comment by Dashed** [comment]
For posterity: https://gitter.im/omniscientjs/omniscient?at=55007d0bd21d125c4b13e141

-----

Might revise API to be `cursor.root().cursor(fullPath)`. Then can be sugared to `cursor.root(fullPath)`.

**Comment by jeffbski** [comment]
Yes, that would be possible to use that that type of syntax, however one reason to stay with something like `cursor.cursorAt(fullPathArray)` is to try to optimize everything for top down subcursor data flow. I actually cursorAt to fail if you try to create a cursor that is not a descendant of your parent. This will let you know that you need to adjust your code or possibly switch to a reference cursor.

So cursorAt will only provide subCursors giving nice top down subcursor optimizations which we can get through using shouldComponentUpdate in React / Omniscient. 

Kind of like the benefits of absolute paths of reference cursors but still using a top down subcursor flow.

**Comment by Dashed** [comment]
https://gitter.im/omniscientjs/omniscient?at=55008b72d21d125c4b13e355

-----

Idea: `cursor.cursor(path, transformPath)` or `cursor.cursor(path, validatePath)`

`transformPath`/`validatePath` are callbacks that take in a path + calling cursor's path, and may either transform/validate the given paths.

**Comment by jeffbski** [comment]
And if we have a way to validate, then that makes `cursor.root(fullPath, validatePath)` a viable option as well. If we have access to keyPath we can create the appropriate restriction for subPaths. 

As @Dashed mentioned in the chat, this separates the concerns. For those that don't care about being top down, a relaxed validation can be used. For a top down optimized flow, the restriction could limit to subpath. This can all be hidden in a simple wrapper like `safeSubCursor(cursor, fullPath)` which calls cursor.root with the proper validate function.

**Comment by jeffbski** [comment]
Currently keyPath isn't public, so it would be ideal if we can get that opened up too. The validatePath fn could be given keyPath as one of its params to allow that subpath check.

**Comment by jeffbski** [comment]
Simplifying further, making `cursor.root(fullPathArr)` always return a cursor and moving the subPath restriction logic into a separate wrapper `subPathCursorFromRoot(cursor, fullPathArr)`, we can have it work either way. 
```javascript
var subPathCursorFromRoot = Cursor.subPathCursorFromRoot;
var subCursor = subPathCursorFromRoot(cursor, ['a', 'b']);
```

Implementation:
```javascript
KeyedCursorPrototype.root =
IndexedCursorPrototype.root = function(keyPath) {
  keyPath = valToKeyPath(keyPath);
  // could check that keyPath equals existing and return this
  var cursor = makeCursor( // call without value
    this._rootData,
    keyPath,
    this._onChange
  );
  return cursor;
}

/**
  shallow array comparison, suitable for array of strings
  */
function arrayStartsWith(arr, arrStart) {
  if (arr.length < arrStart.length) { return false; }
  for(var i = 0; i<arrStart.length; i++) {
    if (arr[i] !== arrStart[i]) { return false; }
  }
  return true;
}

/**
  create a subpath subcursor using full path array,
  assumes access to cursor._keyPath
  returns cursor or null (if not a subpath)
  */
function subPathCursorFromRoot(cursor, fullPathArr) {
  fullPathArr = valToKeyPath(fullPathArr);
  // only allowing subpath cursor
  if (!arrayStartsWith(fullPathArr, cursor._keyPath)) {
    console.error('Error: Invalid path [%s] for subcursor must be subpath of [%s] returning null',
                  fullPathArr, cursor._keyPath);
    return null;
  }
  return cursor.root(fullPathArr);
}

exports.from = cursorFrom;
exports.subPathCursorFromRoot = subPathCursorFromRoot;
```

**Comment by jeffbski** [comment]
# Refining the cursor/subCursor narrative
 
It may be helpful to visualize that a **cursor is like your current working directory** in a file system. You **move to a specific working directory to focus** on the particular subtree of files you are working with. You may move that working directory around **relatively or jump directly to a full path like your HOME** directory. Cursors are similar in that regard that may move them around to different parts of an object tree.

## subCursor defined

I use the term **subCursor to mean a cursor that is created to point to a subdirectory (meaning subset or subtree)** of its parent's tree. A subCursor is used **to drill down deeper** into an object tree.

**Finding the location in the root object tree** might be accomplished by using a **relative subPath** to the current parent. The full path is determined by combining the current path + subPath and that can be applied against the enclosed root object to find the specific subTree.

**An alternative way to jump to the subTree would be to use the full path** instead and go directly there (like changing directly to your HOME working directory). As I stated above, I believe that it is easier to reason about and maintain these absolute paths than to use relative paths in our code.

The **one restriction put on subCursor's by my definition is that you can only go to a subTree** of your current cursor's object tree. This might be akin to having file system permissions that won't let you go up to higher directories.

### subCursor uses 

   - subCursor's are a useful concept for **limiting scope or providing focus** to the necessary data. Some implementations could provide data access restrictions (not allowing access outside the current cursor subtree).
   - subCursors's are especially useful for implementing a **top down data flow** in React or Omniscient where efficient `shouldComponentUpdate()` can be created using quick cursor instance comparison.

## cursor API methods for creating cursors from an existing cursor (current and proposed)

### Currently existing method

   - `cursor.cursor(subPath)` - subCursor down to currentPath + subPath 

### Proposed additions to the Cursor API

  - `cursor.subCursorAt(fullPath)` - **subCursor down to object subtree but locate using full path** from root object. Using invalid fullPath (which is not a subPath of current cursor) could result in returning null OR throw error OR it could be adjustable by adding a flag. (we will choose one of these error handling strategies)
  - `cursor.root(fullPath)` - new **cursor to any location in root object tree using full path** (since this is returning a cursor not a subCursor, it is implied that there are no restrictions on where you can move in the object tree, not confined to current cursor subTree)

**Comment by mikaelbr** [comment]
After a conversation on [Gitter](https://gitter.im/omniscientjs/omniscient?at=55036391090afa0a55608eee), I must say I'm fairly skeptical to having absolute paths from within components. The main issue is that it would imply that components would have to have more knowledge about the data than it really should have.

As mentioned on Gitter:
> So a component could be dependent of data on the contract form `{ foo: { bar: String } }`, right? And you have a child that you know is dependent on a message with the contract `{ bar : String }`. The current component should care where that data is in the tree, it should just know that the data I got contains the data that my child needs.

In other words: It would hurt reusability and couple the components too tight with the data. Consider the following:

```js

var Heading = component((text) => <h1>{text.deref()}</h1>);

var Hello = component(function (cursor) {
  return Heading(cursor.subCursorAt(['some', 'text']); 
});

var structure = immstruct({
  some: { text: 'Hello' },
  other: { text: 'Bye'    },
});

Render.react(Hello(structure.cursor('some')), someElement);

// And use somewhere else
Render.react(Hello(structure.cursor('other')), otherElement);
```

What would happen? Would it give a warning? would it just set the `['some']` part of the cursor as void and only be for visual sake?

The important part is what contract the data is passed as, not where the data is stored in a larger scale, and detailed components should know about the structure as a whole. What if there are lists with many equally structured elements?

I get that this wouldn't be a solution that should be used all the time, and just in some cases, but I think it's encouraging an anti-pattern and allows for too tightly coupled representation and data.

@jeffbski As we discussed on Gitter, I think it would be really good to see an example where you think this would be useful.

**Comment by jeffbski** [comment]
@mikaelbr Yes, thanks for the wonderful discussion as I try to discern the best path here.

When we talked through some of this this evening, I'm thinking maybe there is a better approach possible where by the paths can be provided up front, registered with the initial cursor. It could provide a way to easily create subcursors using the name, and it would keep track of which ones are available as you go deeper (so those that are outside of the subtree would not be available).

I think this approach is even better than using abs path approach since we no longer would have to pass paths down and the app wouldn't need to know details it shouldn't care about. 

I'll write up more details and some examples next week to showcase this, but I think it solves my issues while providing an elegant way to navigate to some of the major subTrees for your app (the named  cursor paths).  You use the named cursors to jump directly to a subtree, then use relative subcursors to navigate within a major section as you do now.

**Comment by jeffbski** [comment]
I implemented an experiment using named cursors that would allow you to register namedPaths into the cursor, so you could jump to a subCursor by name. The named paths are passed to subCursors so you can continue to use the named cursors in children.

Since I only want to support subCursors which are subPath of the existing cursor path, it will check that the named path is a subPath and if not, then will warn and return undefined. This provides the safety check that we are not reaching outside of our subTree.

## Named Cursors

```javascript
var optionalNamedPaths = {
  cat: ['e', 'f']
};
var cursor = Cursor.from(data, ['a', 'b'], newData => {
  data = newData;
}, optionalNamedPaths); // optionally provide namedPaths to factory

// and/or can register additional namedPaths relative to current cursor
cursor.registerNamedPaths({
  foo: ['a', 'b', 'c'],
  bar: ['d']
});

var c1 = cursor.named('foo'); // points to ['a', 'b', 'c']
var cA = cursor.cursor(['a']);
var cABC = cA.named('foo'); // also points to ['a', 'b', 'c']
// logs error with console.warn and return undefined if not subPath
var cFails = cursor.cursor(['d']).named('foo'); // undefined not subPath
```

Implementation is in my namedCursor branch here:
https://github.com/jeffbski/immutable-js/tree/namedCursors/contrib/cursor

**Comment by jeffbski** [comment]
I like the named cursor concept best of all the various solutions above, it seems give me the capabilities I was wanting, however I don't believe that they are necessary for most of my expected use cases.

The way that I would use cursors which is only to register some key subTrees by name, which I would use for different sections on a page. I still plan to use relative subCursors in the deeper components. 

As long as I am using these cursors in the same file and not having to pass down anything but the subCursors, then I don't really need namedCursors.

I can create whatever paths at the top of the file, and just pass that into cursor. The named cursors would be good if trying to implement across file boundaries, passing down to deeper components, but if these are primarily only used in the top file, then they aren't needed.

In my top level app.jsx file, I would simply

```javascript
var blogPath = ['my', 'path', 'to', 'blog', 'items'];
var profilePath = ['another', 'path', 'profile'];

// then later in my file where I want to provide the blog items cursor
var blogCursor = appDataCursor.cursor(blogPath);

// in a different part of same file, I want to provide profileCursor
var profileCursor = appDataCursor.cursor(profilePath);
```

If I find that I am continually needing to go beyond file boundaries and would like to have namedCursors passed down through the cursor mechanism, then I can resurrect this implementation.

So I am going to close this RFC for now since I don't believe it will be necessary in most use cases.

**Comment by mikaelbr** [comment]
Thanks for the follow-up and conclusion @jeffbski ! I agree with your conclusion. I think this is mostly a personal thing which you can solve by doing it the way you have and I don't think there should be an implementation which encourages it (due to the reasons I wrote a couple of days ago).

**Comment by jeffbski** [comment]
Thanks @mikaelbr and @Dashed for the discussion, it helped me think through things more completely.
