### ISSUE TITLE
Combining cursors

### ISSUE THREAD

**Issue by adamschoenemann** [omniscientjs/omniscient#92]
I am often in a situation where a component relies on data from multiple models. For example, a calendar item that needs to know about its date and time, but also user and other metadata. Is there any good way to combine multiple cursors into one, so that the component will rerender when the underlying models change?

Right now I am just passing multiple cursors as props to the component, but it is a rather heavy-handed solution.

**Comment by mikaelbr** [comment]
Hi and thanks for your issue!

I don't really get what the thing is here. You are thinking that passing multiple cursors down to a component is a bad model, or?

So considering a function (which a component really is), how would you solve this issue? Having two references to two different values which your function uses, that would be two arguments right?

```js
function sum (a, b) { return a + b; }
sum(1, 2)
```

And often in JS, when having possibility of arbitrary number of arguments, it's better to have them named, for instance like any AJAX function.

```js
function sum (input) { return input.a + input.b; }
sum({ a: 1, b: 2 })
```

(or with destructuring) 

```js
function sum ({a, b}) { return a + b; }
sum({ a: 1, b: 2 })
```


So your pure function sum, is dependent on two different values which is delivered through a object passed as argument - explicitly you say the function has two inputs. 

The same way if a component is dependent on two different data structures, it should be two different input arguments, just like any function:

```js
var sum = component(({a, b}) => <h1>Sum: {a + b}</h1>);
React.render(sum({ a: 1, b: 2 }), document.body);
```

I think this is the right way to do it, your component is dependent on two values, so it get's passed two values, or am I missing your point?

**Comment by adamschoenemann** [comment]
Thanks for your answer. Even though my original post did not at all communicate it, I think what has got me puzzled is in fact inter-cursor dependencies. For example, consider the good ol' searchbox where you filter a collection of users. It could look like this:


```javascript
var ui = immstruct('ui', {
    search: {
        input: {value: ''}
    }
});

var store = immstruct('store', {
    users: {}
});

ui.on('swap', render);
store.on('swap', render);

var mixin = {
    handleChange(evt) {
        let value = evt.currentTarget.value,
            {store, cursor} = this.props,
            {query} = this.props.statics;

        query(value); // async queries users from e.g. a HTTP API or database and updates the store
        cursor.cursor('input').set('value', value);
    }
};

var SearchBox = component('SearchBox', mixin, function (props) {
    let { cursor, store } = props,
        value = cursor.get('input').get('value'),
        matches = store.filter(x => x.get('name')
                                     .toUpperCase()
                                     .indexOf(value.toUpperCase()) > -1);

    return DOM.div({style: {position: 'relative'}},
        Input(cursor.cursor('input'), {onChange: this.handleChange}),
        Matches(matches)
    );
});

// Input and Matches ...

function render() {
    React.render(
        SearchBox({cursor: ui.cursor('search'), store: store.cursor('users')}),
        document.body
    );
}

render();
```

This is all well and good, but what do you do if you also want the matches to contain state of their own? For example, you might want the user to be able to select several matches. You can't keep that state in the user store, but you also cannot easily add it to the UI struct. Now the UI state is dependent on the state of the store. So what one wants to do is say

```javascript
// Otherwise same as above
var ui = immstruct('ui', {
    search: {
        input: {value: ''},
        matches: [], // <-- added UI state for matches
    }
});

var SearchBox = component('SearchBox', mixin, function (props) {
    let { cursor, store } = props,
        value = cursor.get('input').get('value'),
        storeMatches = store.filter(x => x.get('name')
                                     .toUpperCase()
                                     .indexOf(value.toUpperCase()) > -1);

    cursor.cursor('matches').update(() => {
    	return storeMatches.deref().map(m => Immutable.Map({selected: false}))
    })

    return DOM.div({style: {position: 'relative'}},
        Input(cursor.cursor('input'), {onChange: this.handleChange}),
        Matches({ui: cursor.cursor('matches'), matches})
    );
});
```

Matches now take two cursors: One to its UI state, and one to the database state. The problem is that you cannot do this. You can't (and probably shouldn't!) update a cursor inside `render`. So how do we express that the UI state is dependent on the database state?

Right now I "blindly" index into the `matches` UI state, and initialize the state "lazily" so to speak, as such:

```javascript
var SearchBox = component('SearchBox', mixin, function (props) {
    let { cursor, store } = props;
    let value = cursor.get('input').get('value'),
        matches = store.filter(x => x.get('name').toUpperCase().indexOf(value.toUpperCase()) > -1);

    return DOM.div({style: {position: 'relative'}},
        Input(cursor.cursor('input'), {onChange: this.handleChange}),
        Matches({ui: cursor.cursor('matches'), matches})
    );
});

var Input = component('SearchBox.Input', function (cursor, statics) {
    return DOM.input({
        type: 'text',
        value: cursor.get('value'),
        onChange: statics.onChange,
        className: 'form-control'
    });
});

var Matches = component('SearchBox.Matches', function ({ui, matches}) {
    // "blindly" index into the cursor. At this point, there probably isn't anything there
    let matchArray = matches.map(match => Match('match-' + match.get('id'), {
            ui: ui.cursor(match.get('id').toString()),
            model: match
        })
    ).toArray();
    return DOM.div({className: 'list-group', style: {position: 'absolute', width: '100%'}},
        matchArray
    );

});

var Match = component('SearchBox.Match', {
 
    handleClick() {
        this.props.ui.update(ui => {
            // Check if state is not initialized, and do it if necessary
            if (typeof ui === 'undefined') {
                let initial = {selected: false};
                ui = Immutable.Map(initial);
            }
            return ui.set('selected', !ui.get('selected'));
        });
    },
}, function ({ui, model}) {
    let style = {};
    if (ui.get('selected')) {
        style.backgroundColor = '#fac823';
    }
    return DOM.a({className: 'list-group-item', style: style, onClick:this.handleClick},
        model.get('name')
    );
});
```
This seems less than optimal. I feel like I'm missing something important. I assume I could also use a cursor reference and observe for changes, and then change the UI in response to that, but that also seems awkward to me, especially in large applications.

**Comment by mikaelbr** [comment]
I think this is outside the current scope of Omniscient. Thanks for your discussion and issue!
