### ISSUE TITLE
Reagent style approach / forceUpdateOnState - experimental mixin

### ISSUE THREAD

**Issue by andrewluetgers** [omniscientjs/omniscient#93]
Just posting this here for comment/feedback on the idea. I recently read about [Reagent](https://github.com/reagent-project/reagent) and the differences with Om. [Om No! Trouble in paradise with ClojureScript and React.js](http://getprismatic.com/story/1413760839515) 

This was the titular paragraph.
> Components work best when they know as little data as possible. That way, unnecessary rerendering doesn't have to occur. Om is a very poor fit for this since: (1) app state is in a tree and you need knowledgeof the lowest common ancestor of all the data you need and (2) parents must depend on everything all their children depend on. This results in either (1) the same data in multiple places or (2) a performance hit. This problem was a killer. It was hard to be consistent. It was hard to be performant. We were about to implement a DAG that automatically reconstructs an app state tree by denormalizing ground-truth data when the data changes, but then we discovered that is exactly how Reagent works.
 

This got me thinking and so I whipped up a quick experiment to see if I could make omniscient render each component individually based on its own reference cursors rather than top-down.

[https://gist.github.com/andrewluetgers/7768f74f9b2f2ae8730a](https://gist.github.com/andrewluetgers/7768f74f9b2f2ae8730a)

This approach works and could be useful if you wanted to avoid causing all the parents to render when a child updates. Potentially animation and complex views that are expensive to update may benefit. But this could be complicated and messy to pull off. There could be problems with cyclical behavior. In my testing I removed the usual top down cursor passing, commented out this line

    //appState.on('next-animation-frame', function() {render()})

and just followed the approach as shown in the gist example for all components. I'm curious what others think about this and what Reagent is doing in general.

**Comment by mikaelbr** [comment]
Hi!

As a side-note, AFAIK, that post was before the "reference cursor" implementation in Om?

I've been thinking that rather than locking references to components directly, a partial application pattern could be used instead.

Example using cursors:

```
var MyComp = component(({cursor}) => <h1>{cursor.valueOf()}</h1>);
var PartialedMyComp = partialProps(MyComp, {
  cursor: structure.cursor()
});
```
(see examples: https://gist.github.com/mikaelbr/9dfac0137f5baf294863)

Something like this could also be done for references (but it might require reference-support in `shouldComponentUpdate`. But with partial, you'd still write your components in a referentially transparent way, not binding each component to a specific place in the structure, but you can derivate a new component which is bound to a specific sub-structure. 

PS: The `partialProps` from before doesn't yet support JSX.

**Comment by jeffbski** [comment]
@andrewluetgers Yes, you can definitely use reference cursors to bypass passing everything down through the top. 

I use getChildContext to provide reference cursors down to descendants. Then in the descendant that uses it, subscribe to the updates using setState or forceUpdate to trigger the update on change.

So that is a viable option if you don't want to just pass down everything from the top.

**Comment by andrewluetgers** [comment]
@jeffbski and @mikaelbr thanks for the info, you may be interested in a recent experiment related to this. I noticed this popped up on HN [Efficient Nested React Components](https://news.ycombinator.com/item?id=9242963) and thought it a good opportunity to test out my approach to this problem. Of course the example of updating 10k components is a dramatic abuse of React and ignores the whole point of components, a simple row component would do much good here. But thats not the point of the example, its merely a stress test to see how close to native a worst case scenario is, and how well React can scale in that condition.

[Vanilla JS DOM updates](http://jsfiddle.net/zme8f7k8/4/) (~180 fps)
[React with stupid 10k Components being checked for ShouldComponentUpdate](http://jsfiddle.net/m8n0fpv4/1/) (~6 fps)
[React with sane approach using Row component and immstruct](http://jsfiddle.net/ppy6zyv5/1/) (~75 fps)
[React with my above described approach](http://jsfiddle.net/cbkgf6ab/11/) (~100 fps)

Obviously the last approach is a good improvement over the dumb implementation and even 30% gain over the more sane approach. It is an odd use case of react, a better implementation would probably forego the cell component and just render them all in the row component. Non-the-less this stress-test shows that the approach scales nicely, to 10k reference.observe callbacks registered, one per component. This bypasses all the SCU checks and gets right to the VDOM render and diff for the one component that changed. The stack traces a far shorter as a result as well. On the down side creating so many observe callbacks creates a delay on initialization and chews up memory. 

This is by no means a call to use React this way for these kinds of use-cases, it's clearly better to make smarter use of components and only use react where applicable. A custom game engine in React that performs 1/2 as good and uses 2x the memory and cpu vs a vanilla JS implementation is telling you React is not good for that use case. But I was heartened to see this approach prove itself under pressure.

**Comment by andrewluetgers** [comment]
I have an update to this you may be interested in and PR to immstruct coming related to it but TLDR is that after profiling the above code at 100fps was able to pinpoint listListenerMatching in immstruct as a possible bottleneck. This function used a flat map of paths to store the observer callbacks. when you get a lot of these you can run into a performance issue. I converted the flat map to a tree and gained about 70fps by doing so, which is not too shabby :-) http://plnkr.co/edit/7ObPUFYiwBd841IBdro8?p=preview

**Comment by Dashed** [comment]
@andrewluetgers Damn that's slick! I've been considering something similar to your approach by way of listing and connecting cursor dependencies: `Something.connect(cursors)`. Inspired by: https://github.com/spoike/refluxjs#using-refluxconnect

This was something as a result of custom implementation of Immutable's cursor library with observation at its core: `cursor.on(event, callback)` and `cursor.observe(callback)`. I'm working on this on and off, and am still sketching out the API revision. 

So far, changes to the original Immutable's cursor source code have been minimal, and am able to make `Cursor.from(...)` act like immstruct Structures through overridable internal functions.

**Comment by andrewluetgers** [comment]
Yeah the basic premise here is use a tree structure and traverse the key path to get the callbacks rather than iterating over all paths to collect the callbacks for a given path.

**Comment by Dashed** [comment]
@andrewluetgers Mirroring keypaths by way of a tree is one approach. I've been considering this optimization through another issue: https://github.com/omniscientjs/immstruct/issues/37

If interested, this is the cursor library I'm working on:
https://github.com/Dashed/todomvc-providence/blob/master/src/lib/cursor.js

I'm experimenting it on a todomvc template to get a sense of some use case stories.

Observation done through a similar optimization is done here: https://github.com/Dashed/todomvc-providence/blob/ea00bf6f43b39320c9146051292475557dbfaf9c/src/lib/cursor.js#L368-L383

**Comment by andrewluetgers** [comment]
@Dashed I approve of your ideas and would like to subscribe to your newsletter :-)

**Comment by andrewluetgers** [comment]
I've updated the immstruct changes with a Map data-structure to support objects as keys in the keyPath, performance is unaffected. http://plnkr.co/edit/TRh18pmklgOF8cbunYbj?p=preview
